// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Devices_WiFi_1_H
#define WINRT_Windows_Devices_WiFi_1_H
#include "winrt/impl/Windows.Devices.WiFi.0.h"
WINRT_EXPORT namespace winrt::Windows::Devices::WiFi
{
    struct __declspec(empty_bases) IWiFiAdapter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiAdapter>
    {
        IWiFiAdapter(std::nullptr_t = nullptr) noexcept {}
        IWiFiAdapter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiAdapter(IWiFiAdapter const&) noexcept = default;
        IWiFiAdapter(IWiFiAdapter&&) noexcept = default;
        IWiFiAdapter& operator=(IWiFiAdapter const&) & noexcept = default;
        IWiFiAdapter& operator=(IWiFiAdapter&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiAdapter2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiAdapter2>
    {
        IWiFiAdapter2(std::nullptr_t = nullptr) noexcept {}
        IWiFiAdapter2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiAdapter2(IWiFiAdapter2 const&) noexcept = default;
        IWiFiAdapter2(IWiFiAdapter2&&) noexcept = default;
        IWiFiAdapter2& operator=(IWiFiAdapter2 const&) & noexcept = default;
        IWiFiAdapter2& operator=(IWiFiAdapter2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiAdapterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiAdapterStatics>
    {
        IWiFiAdapterStatics(std::nullptr_t = nullptr) noexcept {}
        IWiFiAdapterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiAdapterStatics(IWiFiAdapterStatics const&) noexcept = default;
        IWiFiAdapterStatics(IWiFiAdapterStatics&&) noexcept = default;
        IWiFiAdapterStatics& operator=(IWiFiAdapterStatics const&) & noexcept = default;
        IWiFiAdapterStatics& operator=(IWiFiAdapterStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiAvailableNetwork :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiAvailableNetwork>
    {
        IWiFiAvailableNetwork(std::nullptr_t = nullptr) noexcept {}
        IWiFiAvailableNetwork(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiAvailableNetwork(IWiFiAvailableNetwork const&) noexcept = default;
        IWiFiAvailableNetwork(IWiFiAvailableNetwork&&) noexcept = default;
        IWiFiAvailableNetwork& operator=(IWiFiAvailableNetwork const&) & noexcept = default;
        IWiFiAvailableNetwork& operator=(IWiFiAvailableNetwork&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiConnectionResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiConnectionResult>
    {
        IWiFiConnectionResult(std::nullptr_t = nullptr) noexcept {}
        IWiFiConnectionResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiConnectionResult(IWiFiConnectionResult const&) noexcept = default;
        IWiFiConnectionResult(IWiFiConnectionResult&&) noexcept = default;
        IWiFiConnectionResult& operator=(IWiFiConnectionResult const&) & noexcept = default;
        IWiFiConnectionResult& operator=(IWiFiConnectionResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiNetworkReport :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiNetworkReport>
    {
        IWiFiNetworkReport(std::nullptr_t = nullptr) noexcept {}
        IWiFiNetworkReport(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiNetworkReport(IWiFiNetworkReport const&) noexcept = default;
        IWiFiNetworkReport(IWiFiNetworkReport&&) noexcept = default;
        IWiFiNetworkReport& operator=(IWiFiNetworkReport const&) & noexcept = default;
        IWiFiNetworkReport& operator=(IWiFiNetworkReport&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiOnDemandHotspotConnectTriggerDetails :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiOnDemandHotspotConnectTriggerDetails>
    {
        IWiFiOnDemandHotspotConnectTriggerDetails(std::nullptr_t = nullptr) noexcept {}
        IWiFiOnDemandHotspotConnectTriggerDetails(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiOnDemandHotspotConnectTriggerDetails(IWiFiOnDemandHotspotConnectTriggerDetails const&) noexcept = default;
        IWiFiOnDemandHotspotConnectTriggerDetails(IWiFiOnDemandHotspotConnectTriggerDetails&&) noexcept = default;
        IWiFiOnDemandHotspotConnectTriggerDetails& operator=(IWiFiOnDemandHotspotConnectTriggerDetails const&) & noexcept = default;
        IWiFiOnDemandHotspotConnectTriggerDetails& operator=(IWiFiOnDemandHotspotConnectTriggerDetails&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiOnDemandHotspotConnectionResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiOnDemandHotspotConnectionResult>
    {
        IWiFiOnDemandHotspotConnectionResult(std::nullptr_t = nullptr) noexcept {}
        IWiFiOnDemandHotspotConnectionResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiOnDemandHotspotConnectionResult(IWiFiOnDemandHotspotConnectionResult const&) noexcept = default;
        IWiFiOnDemandHotspotConnectionResult(IWiFiOnDemandHotspotConnectionResult&&) noexcept = default;
        IWiFiOnDemandHotspotConnectionResult& operator=(IWiFiOnDemandHotspotConnectionResult const&) & noexcept = default;
        IWiFiOnDemandHotspotConnectionResult& operator=(IWiFiOnDemandHotspotConnectionResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiOnDemandHotspotNetwork :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiOnDemandHotspotNetwork>
    {
        IWiFiOnDemandHotspotNetwork(std::nullptr_t = nullptr) noexcept {}
        IWiFiOnDemandHotspotNetwork(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiOnDemandHotspotNetwork(IWiFiOnDemandHotspotNetwork const&) noexcept = default;
        IWiFiOnDemandHotspotNetwork(IWiFiOnDemandHotspotNetwork&&) noexcept = default;
        IWiFiOnDemandHotspotNetwork& operator=(IWiFiOnDemandHotspotNetwork const&) & noexcept = default;
        IWiFiOnDemandHotspotNetwork& operator=(IWiFiOnDemandHotspotNetwork&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiOnDemandHotspotNetworkProperties :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiOnDemandHotspotNetworkProperties>
    {
        IWiFiOnDemandHotspotNetworkProperties(std::nullptr_t = nullptr) noexcept {}
        IWiFiOnDemandHotspotNetworkProperties(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiOnDemandHotspotNetworkProperties(IWiFiOnDemandHotspotNetworkProperties const&) noexcept = default;
        IWiFiOnDemandHotspotNetworkProperties(IWiFiOnDemandHotspotNetworkProperties&&) noexcept = default;
        IWiFiOnDemandHotspotNetworkProperties& operator=(IWiFiOnDemandHotspotNetworkProperties const&) & noexcept = default;
        IWiFiOnDemandHotspotNetworkProperties& operator=(IWiFiOnDemandHotspotNetworkProperties&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiOnDemandHotspotNetworkStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiOnDemandHotspotNetworkStatics>
    {
        IWiFiOnDemandHotspotNetworkStatics(std::nullptr_t = nullptr) noexcept {}
        IWiFiOnDemandHotspotNetworkStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiOnDemandHotspotNetworkStatics(IWiFiOnDemandHotspotNetworkStatics const&) noexcept = default;
        IWiFiOnDemandHotspotNetworkStatics(IWiFiOnDemandHotspotNetworkStatics&&) noexcept = default;
        IWiFiOnDemandHotspotNetworkStatics& operator=(IWiFiOnDemandHotspotNetworkStatics const&) & noexcept = default;
        IWiFiOnDemandHotspotNetworkStatics& operator=(IWiFiOnDemandHotspotNetworkStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWiFiWpsConfigurationResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWiFiWpsConfigurationResult>
    {
        IWiFiWpsConfigurationResult(std::nullptr_t = nullptr) noexcept {}
        IWiFiWpsConfigurationResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWiFiWpsConfigurationResult(IWiFiWpsConfigurationResult const&) noexcept = default;
        IWiFiWpsConfigurationResult(IWiFiWpsConfigurationResult&&) noexcept = default;
        IWiFiWpsConfigurationResult& operator=(IWiFiWpsConfigurationResult const&) & noexcept = default;
        IWiFiWpsConfigurationResult& operator=(IWiFiWpsConfigurationResult&&) & noexcept = default;
    };
}
#endif
