// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_UI_UIAutomation_1_H
#define WINRT_Windows_UI_UIAutomation_1_H
#include "winrt/impl/Windows.UI.UIAutomation.0.h"
WINRT_EXPORT namespace winrt::Windows::UI::UIAutomation
{
    struct __declspec(empty_bases) IAutomationConnection :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationConnection>
    {
        IAutomationConnection(std::nullptr_t = nullptr) noexcept {}
        IAutomationConnection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutomationConnection(IAutomationConnection const&) noexcept = default;
        IAutomationConnection(IAutomationConnection&&) noexcept = default;
        IAutomationConnection& operator=(IAutomationConnection const&) & noexcept = default;
        IAutomationConnection& operator=(IAutomationConnection&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAutomationConnectionBoundObject :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationConnectionBoundObject>
    {
        IAutomationConnectionBoundObject(std::nullptr_t = nullptr) noexcept {}
        IAutomationConnectionBoundObject(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutomationConnectionBoundObject(IAutomationConnectionBoundObject const&) noexcept = default;
        IAutomationConnectionBoundObject(IAutomationConnectionBoundObject&&) noexcept = default;
        IAutomationConnectionBoundObject& operator=(IAutomationConnectionBoundObject const&) & noexcept = default;
        IAutomationConnectionBoundObject& operator=(IAutomationConnectionBoundObject&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAutomationElement :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationElement>
    {
        IAutomationElement(std::nullptr_t = nullptr) noexcept {}
        IAutomationElement(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutomationElement(IAutomationElement const&) noexcept = default;
        IAutomationElement(IAutomationElement&&) noexcept = default;
        IAutomationElement& operator=(IAutomationElement const&) & noexcept = default;
        IAutomationElement& operator=(IAutomationElement&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAutomationTextRange :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationTextRange>
    {
        IAutomationTextRange(std::nullptr_t = nullptr) noexcept {}
        IAutomationTextRange(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutomationTextRange(IAutomationTextRange const&) noexcept = default;
        IAutomationTextRange(IAutomationTextRange&&) noexcept = default;
        IAutomationTextRange& operator=(IAutomationTextRange const&) & noexcept = default;
        IAutomationTextRange& operator=(IAutomationTextRange&&) & noexcept = default;
    };
}
#endif
