// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Management_Deployment_1_H
#define WINRT_Windows_Management_Deployment_1_H
#include "winrt/impl/Windows.Management.Deployment.0.h"
WINRT_EXPORT namespace winrt::Windows::Management::Deployment
{
    struct __declspec(empty_bases) IAddPackageOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAddPackageOptions>
    {
        IAddPackageOptions(std::nullptr_t = nullptr) noexcept {}
        IAddPackageOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAddPackageOptions(IAddPackageOptions const&) noexcept = default;
        IAddPackageOptions(IAddPackageOptions&&) noexcept = default;
        IAddPackageOptions& operator=(IAddPackageOptions const&) & noexcept = default;
        IAddPackageOptions& operator=(IAddPackageOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAddPackageOptions2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAddPackageOptions2>
    {
        IAddPackageOptions2(std::nullptr_t = nullptr) noexcept {}
        IAddPackageOptions2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAddPackageOptions2(IAddPackageOptions2 const&) noexcept = default;
        IAddPackageOptions2(IAddPackageOptions2&&) noexcept = default;
        IAddPackageOptions2& operator=(IAddPackageOptions2 const&) & noexcept = default;
        IAddPackageOptions2& operator=(IAddPackageOptions2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppInstallerManager :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppInstallerManager>
    {
        IAppInstallerManager(std::nullptr_t = nullptr) noexcept {}
        IAppInstallerManager(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppInstallerManager(IAppInstallerManager const&) noexcept = default;
        IAppInstallerManager(IAppInstallerManager&&) noexcept = default;
        IAppInstallerManager& operator=(IAppInstallerManager const&) & noexcept = default;
        IAppInstallerManager& operator=(IAppInstallerManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppInstallerManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppInstallerManagerStatics>
    {
        IAppInstallerManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IAppInstallerManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppInstallerManagerStatics(IAppInstallerManagerStatics const&) noexcept = default;
        IAppInstallerManagerStatics(IAppInstallerManagerStatics&&) noexcept = default;
        IAppInstallerManagerStatics& operator=(IAppInstallerManagerStatics const&) & noexcept = default;
        IAppInstallerManagerStatics& operator=(IAppInstallerManagerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAutoUpdateSettingsOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutoUpdateSettingsOptions>
    {
        IAutoUpdateSettingsOptions(std::nullptr_t = nullptr) noexcept {}
        IAutoUpdateSettingsOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutoUpdateSettingsOptions(IAutoUpdateSettingsOptions const&) noexcept = default;
        IAutoUpdateSettingsOptions(IAutoUpdateSettingsOptions&&) noexcept = default;
        IAutoUpdateSettingsOptions& operator=(IAutoUpdateSettingsOptions const&) & noexcept = default;
        IAutoUpdateSettingsOptions& operator=(IAutoUpdateSettingsOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAutoUpdateSettingsOptionsStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutoUpdateSettingsOptionsStatics>
    {
        IAutoUpdateSettingsOptionsStatics(std::nullptr_t = nullptr) noexcept {}
        IAutoUpdateSettingsOptionsStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutoUpdateSettingsOptionsStatics(IAutoUpdateSettingsOptionsStatics const&) noexcept = default;
        IAutoUpdateSettingsOptionsStatics(IAutoUpdateSettingsOptionsStatics&&) noexcept = default;
        IAutoUpdateSettingsOptionsStatics& operator=(IAutoUpdateSettingsOptionsStatics const&) & noexcept = default;
        IAutoUpdateSettingsOptionsStatics& operator=(IAutoUpdateSettingsOptionsStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IDeploymentResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentResult>
    {
        IDeploymentResult(std::nullptr_t = nullptr) noexcept {}
        IDeploymentResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IDeploymentResult(IDeploymentResult const&) noexcept = default;
        IDeploymentResult(IDeploymentResult&&) noexcept = default;
        IDeploymentResult& operator=(IDeploymentResult const&) & noexcept = default;
        IDeploymentResult& operator=(IDeploymentResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IDeploymentResult2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IDeploymentResult2>
    {
        IDeploymentResult2(std::nullptr_t = nullptr) noexcept {}
        IDeploymentResult2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IDeploymentResult2(IDeploymentResult2 const&) noexcept = default;
        IDeploymentResult2(IDeploymentResult2&&) noexcept = default;
        IDeploymentResult2& operator=(IDeploymentResult2 const&) & noexcept = default;
        IDeploymentResult2& operator=(IDeploymentResult2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageAllUserProvisioningOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageAllUserProvisioningOptions>
    {
        IPackageAllUserProvisioningOptions(std::nullptr_t = nullptr) noexcept {}
        IPackageAllUserProvisioningOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageAllUserProvisioningOptions(IPackageAllUserProvisioningOptions const&) noexcept = default;
        IPackageAllUserProvisioningOptions(IPackageAllUserProvisioningOptions&&) noexcept = default;
        IPackageAllUserProvisioningOptions& operator=(IPackageAllUserProvisioningOptions const&) & noexcept = default;
        IPackageAllUserProvisioningOptions& operator=(IPackageAllUserProvisioningOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageAllUserProvisioningOptions2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageAllUserProvisioningOptions2>
    {
        IPackageAllUserProvisioningOptions2(std::nullptr_t = nullptr) noexcept {}
        IPackageAllUserProvisioningOptions2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageAllUserProvisioningOptions2(IPackageAllUserProvisioningOptions2 const&) noexcept = default;
        IPackageAllUserProvisioningOptions2(IPackageAllUserProvisioningOptions2&&) noexcept = default;
        IPackageAllUserProvisioningOptions2& operator=(IPackageAllUserProvisioningOptions2 const&) & noexcept = default;
        IPackageAllUserProvisioningOptions2& operator=(IPackageAllUserProvisioningOptions2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager>
    {
        IPackageManager(std::nullptr_t = nullptr) noexcept {}
        IPackageManager(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager(IPackageManager const&) noexcept = default;
        IPackageManager(IPackageManager&&) noexcept = default;
        IPackageManager& operator=(IPackageManager const&) & noexcept = default;
        IPackageManager& operator=(IPackageManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager10 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager10>
    {
        IPackageManager10(std::nullptr_t = nullptr) noexcept {}
        IPackageManager10(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager10(IPackageManager10 const&) noexcept = default;
        IPackageManager10(IPackageManager10&&) noexcept = default;
        IPackageManager10& operator=(IPackageManager10 const&) & noexcept = default;
        IPackageManager10& operator=(IPackageManager10&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager11 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager11>
    {
        IPackageManager11(std::nullptr_t = nullptr) noexcept {}
        IPackageManager11(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager11(IPackageManager11 const&) noexcept = default;
        IPackageManager11(IPackageManager11&&) noexcept = default;
        IPackageManager11& operator=(IPackageManager11 const&) & noexcept = default;
        IPackageManager11& operator=(IPackageManager11&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager12 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager12>
    {
        IPackageManager12(std::nullptr_t = nullptr) noexcept {}
        IPackageManager12(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager12(IPackageManager12 const&) noexcept = default;
        IPackageManager12(IPackageManager12&&) noexcept = default;
        IPackageManager12& operator=(IPackageManager12 const&) & noexcept = default;
        IPackageManager12& operator=(IPackageManager12&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager2>
    {
        IPackageManager2(std::nullptr_t = nullptr) noexcept {}
        IPackageManager2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager2(IPackageManager2 const&) noexcept = default;
        IPackageManager2(IPackageManager2&&) noexcept = default;
        IPackageManager2& operator=(IPackageManager2 const&) & noexcept = default;
        IPackageManager2& operator=(IPackageManager2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager3>
    {
        IPackageManager3(std::nullptr_t = nullptr) noexcept {}
        IPackageManager3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager3(IPackageManager3 const&) noexcept = default;
        IPackageManager3(IPackageManager3&&) noexcept = default;
        IPackageManager3& operator=(IPackageManager3 const&) & noexcept = default;
        IPackageManager3& operator=(IPackageManager3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager4 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager4>
    {
        IPackageManager4(std::nullptr_t = nullptr) noexcept {}
        IPackageManager4(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager4(IPackageManager4 const&) noexcept = default;
        IPackageManager4(IPackageManager4&&) noexcept = default;
        IPackageManager4& operator=(IPackageManager4 const&) & noexcept = default;
        IPackageManager4& operator=(IPackageManager4&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager5 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager5>
    {
        IPackageManager5(std::nullptr_t = nullptr) noexcept {}
        IPackageManager5(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager5(IPackageManager5 const&) noexcept = default;
        IPackageManager5(IPackageManager5&&) noexcept = default;
        IPackageManager5& operator=(IPackageManager5 const&) & noexcept = default;
        IPackageManager5& operator=(IPackageManager5&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager6 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager6>
    {
        IPackageManager6(std::nullptr_t = nullptr) noexcept {}
        IPackageManager6(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager6(IPackageManager6 const&) noexcept = default;
        IPackageManager6(IPackageManager6&&) noexcept = default;
        IPackageManager6& operator=(IPackageManager6 const&) & noexcept = default;
        IPackageManager6& operator=(IPackageManager6&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager7 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager7>
    {
        IPackageManager7(std::nullptr_t = nullptr) noexcept {}
        IPackageManager7(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager7(IPackageManager7 const&) noexcept = default;
        IPackageManager7(IPackageManager7&&) noexcept = default;
        IPackageManager7& operator=(IPackageManager7 const&) & noexcept = default;
        IPackageManager7& operator=(IPackageManager7&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager8 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager8>
    {
        IPackageManager8(std::nullptr_t = nullptr) noexcept {}
        IPackageManager8(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager8(IPackageManager8 const&) noexcept = default;
        IPackageManager8(IPackageManager8&&) noexcept = default;
        IPackageManager8& operator=(IPackageManager8 const&) & noexcept = default;
        IPackageManager8& operator=(IPackageManager8&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManager9 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManager9>
    {
        IPackageManager9(std::nullptr_t = nullptr) noexcept {}
        IPackageManager9(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManager9(IPackageManager9 const&) noexcept = default;
        IPackageManager9(IPackageManager9&&) noexcept = default;
        IPackageManager9& operator=(IPackageManager9 const&) & noexcept = default;
        IPackageManager9& operator=(IPackageManager9&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageManagerDebugSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageManagerDebugSettings>
    {
        IPackageManagerDebugSettings(std::nullptr_t = nullptr) noexcept {}
        IPackageManagerDebugSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageManagerDebugSettings(IPackageManagerDebugSettings const&) noexcept = default;
        IPackageManagerDebugSettings(IPackageManagerDebugSettings&&) noexcept = default;
        IPackageManagerDebugSettings& operator=(IPackageManagerDebugSettings const&) & noexcept = default;
        IPackageManagerDebugSettings& operator=(IPackageManagerDebugSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageUserInformation :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageUserInformation>
    {
        IPackageUserInformation(std::nullptr_t = nullptr) noexcept {}
        IPackageUserInformation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageUserInformation(IPackageUserInformation const&) noexcept = default;
        IPackageUserInformation(IPackageUserInformation&&) noexcept = default;
        IPackageUserInformation& operator=(IPackageUserInformation const&) & noexcept = default;
        IPackageUserInformation& operator=(IPackageUserInformation&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageVolume :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageVolume>
    {
        IPackageVolume(std::nullptr_t = nullptr) noexcept {}
        IPackageVolume(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageVolume(IPackageVolume const&) noexcept = default;
        IPackageVolume(IPackageVolume&&) noexcept = default;
        IPackageVolume& operator=(IPackageVolume const&) & noexcept = default;
        IPackageVolume& operator=(IPackageVolume&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPackageVolume2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPackageVolume2>
    {
        IPackageVolume2(std::nullptr_t = nullptr) noexcept {}
        IPackageVolume2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPackageVolume2(IPackageVolume2 const&) noexcept = default;
        IPackageVolume2(IPackageVolume2&&) noexcept = default;
        IPackageVolume2& operator=(IPackageVolume2 const&) & noexcept = default;
        IPackageVolume2& operator=(IPackageVolume2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRegisterPackageOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRegisterPackageOptions>
    {
        IRegisterPackageOptions(std::nullptr_t = nullptr) noexcept {}
        IRegisterPackageOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRegisterPackageOptions(IRegisterPackageOptions const&) noexcept = default;
        IRegisterPackageOptions(IRegisterPackageOptions&&) noexcept = default;
        IRegisterPackageOptions& operator=(IRegisterPackageOptions const&) & noexcept = default;
        IRegisterPackageOptions& operator=(IRegisterPackageOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRegisterPackageOptions2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRegisterPackageOptions2>
    {
        IRegisterPackageOptions2(std::nullptr_t = nullptr) noexcept {}
        IRegisterPackageOptions2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRegisterPackageOptions2(IRegisterPackageOptions2 const&) noexcept = default;
        IRegisterPackageOptions2(IRegisterPackageOptions2&&) noexcept = default;
        IRegisterPackageOptions2& operator=(IRegisterPackageOptions2 const&) & noexcept = default;
        IRegisterPackageOptions2& operator=(IRegisterPackageOptions2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemovePackageOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemovePackageOptions>
    {
        IRemovePackageOptions(std::nullptr_t = nullptr) noexcept {}
        IRemovePackageOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemovePackageOptions(IRemovePackageOptions const&) noexcept = default;
        IRemovePackageOptions(IRemovePackageOptions&&) noexcept = default;
        IRemovePackageOptions& operator=(IRemovePackageOptions const&) & noexcept = default;
        IRemovePackageOptions& operator=(IRemovePackageOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemovePackageOptions2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemovePackageOptions2>
    {
        IRemovePackageOptions2(std::nullptr_t = nullptr) noexcept {}
        IRemovePackageOptions2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemovePackageOptions2(IRemovePackageOptions2 const&) noexcept = default;
        IRemovePackageOptions2(IRemovePackageOptions2&&) noexcept = default;
        IRemovePackageOptions2& operator=(IRemovePackageOptions2 const&) & noexcept = default;
        IRemovePackageOptions2& operator=(IRemovePackageOptions2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IStagePackageOptions :
        Windows::Foundation::IInspectable,
        impl::consume_t<IStagePackageOptions>
    {
        IStagePackageOptions(std::nullptr_t = nullptr) noexcept {}
        IStagePackageOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IStagePackageOptions(IStagePackageOptions const&) noexcept = default;
        IStagePackageOptions(IStagePackageOptions&&) noexcept = default;
        IStagePackageOptions& operator=(IStagePackageOptions const&) & noexcept = default;
        IStagePackageOptions& operator=(IStagePackageOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IStagePackageOptions2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IStagePackageOptions2>
    {
        IStagePackageOptions2(std::nullptr_t = nullptr) noexcept {}
        IStagePackageOptions2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IStagePackageOptions2(IStagePackageOptions2 const&) noexcept = default;
        IStagePackageOptions2(IStagePackageOptions2&&) noexcept = default;
        IStagePackageOptions2& operator=(IStagePackageOptions2 const&) & noexcept = default;
        IStagePackageOptions2& operator=(IStagePackageOptions2&&) & noexcept = default;
    };
}
#endif
