// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_VirtualPrinterAppSdk_AppInfo()
{
    return winrt::detach_abi(winrt::make<winrt::VirtualPrinterAppSdk::factory_implementation::AppInfo>());
}
WINRT_EXPORT namespace winrt::VirtualPrinterAppSdk
{
    AppInfo::AppInfo() :
        AppInfo(make<VirtualPrinterAppSdk::implementation::AppInfo>())
    {
    }
}
