// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

void* winrt_make_XpsUtil_XpsPageWatermarker()
{
    return winrt::detach_abi(winrt::make<winrt::XpsUtil::factory_implementation::XpsPageWatermarker>());
}
WINRT_EXPORT namespace winrt::XpsUtil
{
    XpsPageWatermarker::XpsPageWatermarker() :
        XpsPageWatermarker(make<XpsUtil::implementation::XpsPageWatermarker>())
    {
    }
}
