// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_BackgroundTasks_H
#define WINRT_BackgroundTasks_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240405.15"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240405.15"
#include "winrt/impl/Windows.ApplicationModel.Background.2.h"
#include "winrt/impl/Windows.Devices.Printers.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/BackgroundTasks.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::GetWatermarkTextPropertiesFromLocalStorage(hstring& watermarkText, int32_t& fontSize, double& xPos, double& yPos) const
    {
        bool result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->GetWatermarkTextPropertiesFromLocalStorage(impl::bind_out(watermarkText), &fontSize, &xPos, &yPos, &result));
        return result;
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::SaveWatermarkTextPropertiesToLocalStorage(param::hstring const& Watermark, int32_t fontSize, double xPos, double yPos) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->SaveWatermarkTextPropertiesToLocalStorage(*(void**)(&Watermark), fontSize, xPos, yPos));
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::ResetWatermarkTextAndImage() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->ResetWatermarkTextAndImage());
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::SaveImagePropertiesToLocalStorage(param::hstring const& imageFile, double dpiX, double dpiY, int32_t imageWidth, int32_t imageHeight) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->SaveImagePropertiesToLocalStorage(*(void**)(&imageFile), dpiX, dpiY, imageWidth, imageHeight));
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::GetImagePropertiesFromLocalStorage(hstring& imageFile, double& dpiX, double& dpiY, int32_t& width, int32_t& height) const
    {
        bool result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->GetImagePropertiesFromLocalStorage(impl::bind_out(imageFile), &dpiX, &dpiY, &width, &height, &result));
        return result;
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::SaveCustomIppAttributesToLocalStorage(param::map<hstring, winrt::Windows::Devices::Printers::IppAttributeValue> const& attributes) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->SaveCustomIppAttributesToLocalStorage(*(void**)(&attributes)));
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::GetCustomIppAttributesFromLocalStorage() const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->GetCustomIppAttributesFromLocalStorage(&result));
        return winrt::Windows::Foundation::Collections::IMap<hstring, winrt::Windows::Devices::Printers::IppAttributeValue>{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::GetDisableIppCompression(bool& disableIppCompression) const
    {
        bool result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->GetDisableIppCompression(&disableIppCompression, &result));
        return result;
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::SetDisableIppCompression(bool disableIppCompression) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->SetDisableIppCompression(disableIppCompression));
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::GetEnablePsaCustomToast(bool& enablePsaCustomToast) const
    {
        bool result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->GetEnablePsaCustomToast(&enablePsaCustomToast, &result));
        return result;
    }
    template <typename D> auto consume_BackgroundTasks_ILocalStorageHelperStatics<D>::SetEnablePsaCustomToast(bool enablePsaCustomToast) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BackgroundTasks::ILocalStorageHelperStatics)->SetEnablePsaCustomToast(enablePsaCustomToast));
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BackgroundTasks::ILocalStorageHelper> : produce_base<D, winrt::BackgroundTasks::ILocalStorageHelper>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BackgroundTasks::ILocalStorageHelperStatics> : produce_base<D, winrt::BackgroundTasks::ILocalStorageHelperStatics>
    {
        int32_t __stdcall GetWatermarkTextPropertiesFromLocalStorage(void** watermarkText, int32_t* fontSize, double* xPos, double* yPos, bool* result) noexcept final try
        {
            clear_abi(watermarkText);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<bool>(this->shim().GetWatermarkTextPropertiesFromLocalStorage(*reinterpret_cast<hstring*>(watermarkText), *fontSize, *xPos, *yPos));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SaveWatermarkTextPropertiesToLocalStorage(void* Watermark, int32_t fontSize, double xPos, double yPos) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SaveWatermarkTextPropertiesToLocalStorage(*reinterpret_cast<hstring const*>(&Watermark), fontSize, xPos, yPos);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall ResetWatermarkTextAndImage() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ResetWatermarkTextAndImage();
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SaveImagePropertiesToLocalStorage(void* imageFile, double dpiX, double dpiY, int32_t imageWidth, int32_t imageHeight) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SaveImagePropertiesToLocalStorage(*reinterpret_cast<hstring const*>(&imageFile), dpiX, dpiY, imageWidth, imageHeight);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetImagePropertiesFromLocalStorage(void** imageFile, double* dpiX, double* dpiY, int32_t* width, int32_t* height, bool* result) noexcept final try
        {
            clear_abi(imageFile);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<bool>(this->shim().GetImagePropertiesFromLocalStorage(*reinterpret_cast<hstring*>(imageFile), *dpiX, *dpiY, *width, *height));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SaveCustomIppAttributesToLocalStorage(void* attributes) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SaveCustomIppAttributesToLocalStorage(*reinterpret_cast<winrt::Windows::Foundation::Collections::IMap<hstring, winrt::Windows::Devices::Printers::IppAttributeValue> const*>(&attributes));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetCustomIppAttributesFromLocalStorage(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Foundation::Collections::IMap<hstring, winrt::Windows::Devices::Printers::IppAttributeValue>>(this->shim().GetCustomIppAttributesFromLocalStorage());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetDisableIppCompression(bool* disableIppCompression, bool* result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<bool>(this->shim().GetDisableIppCompression(*disableIppCompression));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SetDisableIppCompression(bool disableIppCompression) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetDisableIppCompression(disableIppCompression);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetEnablePsaCustomToast(bool* enablePsaCustomToast, bool* result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<bool>(this->shim().GetEnablePsaCustomToast(*enablePsaCustomToast));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SetEnablePsaCustomToast(bool enablePsaCustomToast) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetEnablePsaCustomToast(enablePsaCustomToast);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BackgroundTasks::IPrintSupportExtension> : produce_base<D, winrt::BackgroundTasks::IPrintSupportExtension>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BackgroundTasks::IVirtualPrinterBgTask> : produce_base<D, winrt::BackgroundTasks::IVirtualPrinterBgTask>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BackgroundTasks::IWorkflowBgTask> : produce_base<D, winrt::BackgroundTasks::IWorkflowBgTask>
    {
    };
#endif
}
WINRT_EXPORT namespace winrt::BackgroundTasks
{
    inline LocalStorageHelper::LocalStorageHelper() :
        LocalStorageHelper(impl::call_factory_cast<LocalStorageHelper(*)(winrt::Windows::Foundation::IActivationFactory const&), LocalStorageHelper>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<LocalStorageHelper>(); }))
    {
    }
    inline auto LocalStorageHelper::GetWatermarkTextPropertiesFromLocalStorage(hstring& watermarkText, int32_t& fontSize, double& xPos, double& yPos)
    {
        return impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.GetWatermarkTextPropertiesFromLocalStorage(watermarkText, fontSize, xPos, yPos); });
    }
    inline auto LocalStorageHelper::SaveWatermarkTextPropertiesToLocalStorage(param::hstring const& Watermark, int32_t fontSize, double xPos, double yPos)
    {
        impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.SaveWatermarkTextPropertiesToLocalStorage(Watermark, fontSize, xPos, yPos); });
    }
    inline auto LocalStorageHelper::ResetWatermarkTextAndImage()
    {
        impl::call_factory_cast<void(*)(ILocalStorageHelperStatics const&), LocalStorageHelper, ILocalStorageHelperStatics>([](ILocalStorageHelperStatics const& f) { return f.ResetWatermarkTextAndImage(); });
    }
    inline auto LocalStorageHelper::SaveImagePropertiesToLocalStorage(param::hstring const& imageFile, double dpiX, double dpiY, int32_t imageWidth, int32_t imageHeight)
    {
        impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.SaveImagePropertiesToLocalStorage(imageFile, dpiX, dpiY, imageWidth, imageHeight); });
    }
    inline auto LocalStorageHelper::GetImagePropertiesFromLocalStorage(hstring& imageFile, double& dpiX, double& dpiY, int32_t& width, int32_t& height)
    {
        return impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.GetImagePropertiesFromLocalStorage(imageFile, dpiX, dpiY, width, height); });
    }
    inline auto LocalStorageHelper::SaveCustomIppAttributesToLocalStorage(param::map<hstring, winrt::Windows::Devices::Printers::IppAttributeValue> const& attributes)
    {
        impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.SaveCustomIppAttributesToLocalStorage(attributes); });
    }
    inline auto LocalStorageHelper::GetCustomIppAttributesFromLocalStorage()
    {
        return impl::call_factory_cast<winrt::Windows::Foundation::Collections::IMap<hstring, winrt::Windows::Devices::Printers::IppAttributeValue>(*)(ILocalStorageHelperStatics const&), LocalStorageHelper, ILocalStorageHelperStatics>([](ILocalStorageHelperStatics const& f) { return f.GetCustomIppAttributesFromLocalStorage(); });
    }
    inline auto LocalStorageHelper::GetDisableIppCompression(bool& disableIppCompression)
    {
        return impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.GetDisableIppCompression(disableIppCompression); });
    }
    inline auto LocalStorageHelper::SetDisableIppCompression(bool disableIppCompression)
    {
        impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.SetDisableIppCompression(disableIppCompression); });
    }
    inline auto LocalStorageHelper::GetEnablePsaCustomToast(bool& enablePsaCustomToast)
    {
        return impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.GetEnablePsaCustomToast(enablePsaCustomToast); });
    }
    inline auto LocalStorageHelper::SetEnablePsaCustomToast(bool enablePsaCustomToast)
    {
        impl::call_factory<LocalStorageHelper, ILocalStorageHelperStatics>([&](ILocalStorageHelperStatics const& f) { return f.SetEnablePsaCustomToast(enablePsaCustomToast); });
    }
    inline PrintSupportExtension::PrintSupportExtension() :
        PrintSupportExtension(impl::call_factory_cast<PrintSupportExtension(*)(winrt::Windows::Foundation::IActivationFactory const&), PrintSupportExtension>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<PrintSupportExtension>(); }))
    {
    }
    inline VirtualPrinterBgTask::VirtualPrinterBgTask() :
        VirtualPrinterBgTask(impl::call_factory_cast<VirtualPrinterBgTask(*)(winrt::Windows::Foundation::IActivationFactory const&), VirtualPrinterBgTask>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<VirtualPrinterBgTask>(); }))
    {
    }
    inline WorkflowBgTask::WorkflowBgTask() :
        WorkflowBgTask(impl::call_factory_cast<WorkflowBgTask(*)(winrt::Windows::Foundation::IActivationFactory const&), WorkflowBgTask>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<WorkflowBgTask>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::BackgroundTasks::ILocalStorageHelper> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::ILocalStorageHelperStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::IPrintSupportExtension> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::IVirtualPrinterBgTask> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::IWorkflowBgTask> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::LocalStorageHelper> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::PrintSupportExtension> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::VirtualPrinterBgTask> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BackgroundTasks::WorkflowBgTask> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
