// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_VirtualPrinterAppSdk_H
#define WINRT_VirtualPrinterAppSdk_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240405.15"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240405.15"
#include "winrt/impl/Microsoft.UI.Composition.2.h"
#include "winrt/impl/Microsoft.UI.Windowing.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Input.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Graphics.Printing.PrintSupport.2.h"
#include "winrt/impl/Windows.Graphics.Printing.Workflow.2.h"
#include "winrt/impl/XpsUtil.2.h"
#include "winrt/impl/VirtualPrinterAppSdk.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_VirtualPrinterAppSdk_IJobActivationMainPage<D>::CloseDialog() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IJobActivationMainPage)->CloseDialog());
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IJobActivationMainPage<D>::PdlDataEventArgs() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IJobActivationMainPage)->get_PdlDataEventArgs(&value));
        return winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowPdlDataAvailableEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IJobActivationMainPage<D>::VirtualPrinterPdlDataEventArgs() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IJobActivationMainPage)->get_VirtualPrinterPdlDataEventArgs(&value));
        return winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowVirtualPrinterUIEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IJobActivationMainPage<D>::JobNotificationEventArgs() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IJobActivationMainPage)->get_JobNotificationEventArgs(&value));
        return winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowJobNotificationEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IJobActivationMainPage<D>::ActivationKind() const
    {
        winrt::VirtualPrinterAppSdk::JobActivationKind value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IJobActivationMainPage)->get_ActivationKind(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IMainWindow<D>::WorkflowJobActivatedArgs() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IMainWindow)->get_WorkflowJobActivatedArgs(&value));
        return winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowJobActivatedEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IMainWindow<D>::MyAppWindow() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IMainWindow)->get_MyAppWindow(&value));
        return winrt::Microsoft::UI::Windowing::AppWindow{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IMainWindowFactory<D>::CreateInstance(winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowJobActivatedEventArgs const& args) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IMainWindowFactory)->CreateInstance(*(void**)(&args), &value));
        return winrt::VirtualPrinterAppSdk::MainWindow{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::PrevButtonClicked(winrt::Microsoft::UI::Xaml::RoutedEventHandler const& handler) const
    {
        winrt::event_token token{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->add_PrevButtonClicked(*(void**)(&handler), put_abi(token)));
        return token;
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::PrevButtonClicked(auto_revoke_t, winrt::Microsoft::UI::Xaml::RoutedEventHandler const& handler) const
    {
        return impl::make_event_revoker<D, PrevButtonClicked_revoker>(this, PrevButtonClicked(handler));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::PrevButtonClicked(winrt::event_token const& token) const noexcept
    {
        WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->remove_PrevButtonClicked(impl::bind_in(token));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::NextButtonClicked(winrt::Microsoft::UI::Xaml::RoutedEventHandler const& handler) const
    {
        winrt::event_token token{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->add_NextButtonClicked(*(void**)(&handler), put_abi(token)));
        return token;
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::NextButtonClicked(auto_revoke_t, winrt::Microsoft::UI::Xaml::RoutedEventHandler const& handler) const
    {
        return impl::make_event_revoker<D, NextButtonClicked_revoker>(this, NextButtonClicked(handler));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::NextButtonClicked(winrt::event_token const& token) const noexcept
    {
        WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->remove_NextButtonClicked(impl::bind_in(token));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::TotalPages() const
    {
        uint32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->get_TotalPages(&value));
        return value;
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::TotalPages(uint32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->put_TotalPages(value));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::CurrentPage() const
    {
        uint32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->get_CurrentPage(&value));
        return value;
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPreviewPaginationControl<D>::CurrentPage(uint32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPreviewPaginationControl)->put_CurrentPage(value));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IPrinterSettingsFactory<D>::CreateInstance(winrt::Windows::Graphics::Printing::PrintSupport::PrintSupportSettingsActivatedEventArgs const& args) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IPrinterSettingsFactory)->CreateInstance(*(void**)(&args), &value));
        return winrt::VirtualPrinterAppSdk::PrinterSettings{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IWatermarkPreviewControl<D>::WatermarkPreviewTapped(winrt::Microsoft::UI::Xaml::Input::TappedEventHandler const& handler) const
    {
        winrt::event_token token{};
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl)->add_WatermarkPreviewTapped(*(void**)(&handler), put_abi(token)));
        return token;
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IWatermarkPreviewControl<D>::WatermarkPreviewTapped(auto_revoke_t, winrt::Microsoft::UI::Xaml::Input::TappedEventHandler const& handler) const
    {
        return impl::make_event_revoker<D, WatermarkPreviewTapped_revoker>(this, WatermarkPreviewTapped(handler));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IWatermarkPreviewControl<D>::WatermarkPreviewTapped(winrt::event_token const& token) const noexcept
    {
        WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl)->remove_WatermarkPreviewTapped(impl::bind_in(token));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IWatermarkPreviewControl<D>::PreviewPage(winrt::XpsUtil::XpsPageWrapper const& pageWrapper) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl)->PreviewPage(*(void**)(&pageWrapper)));
    }
    template <typename D> auto consume_VirtualPrinterAppSdk_IWatermarkPreviewControl<D>::StartPreviewRefresh() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl)->StartPreviewRefresh());
    }
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IAppInfo> : produce_base<D, winrt::VirtualPrinterAppSdk::IAppInfo>
    {
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IJobActivationMainPage> : produce_base<D, winrt::VirtualPrinterAppSdk::IJobActivationMainPage>
    {
        int32_t __stdcall CloseDialog() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CloseDialog();
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_PdlDataEventArgs(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowPdlDataAvailableEventArgs>(this->shim().PdlDataEventArgs());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_VirtualPrinterPdlDataEventArgs(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowVirtualPrinterUIEventArgs>(this->shim().VirtualPrinterPdlDataEventArgs());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_JobNotificationEventArgs(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowJobNotificationEventArgs>(this->shim().JobNotificationEventArgs());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_ActivationKind(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::VirtualPrinterAppSdk::JobActivationKind>(this->shim().ActivationKind());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IMainWindow> : produce_base<D, winrt::VirtualPrinterAppSdk::IMainWindow>
    {
        int32_t __stdcall get_WorkflowJobActivatedArgs(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowJobActivatedEventArgs>(this->shim().WorkflowJobActivatedArgs());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_MyAppWindow(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::UI::Windowing::AppWindow>(this->shim().MyAppWindow());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IMainWindowFactory> : produce_base<D, winrt::VirtualPrinterAppSdk::IMainWindowFactory>
    {
        int32_t __stdcall CreateInstance(void* args, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::VirtualPrinterAppSdk::MainWindow>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Graphics::Printing::Workflow::PrintWorkflowJobActivatedEventArgs const*>(&args)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IPreviewPaginationControl> : produce_base<D, winrt::VirtualPrinterAppSdk::IPreviewPaginationControl>
    {
        int32_t __stdcall add_PrevButtonClicked(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().PrevButtonClicked(*reinterpret_cast<winrt::Microsoft::UI::Xaml::RoutedEventHandler const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall remove_PrevButtonClicked(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PrevButtonClicked(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        int32_t __stdcall add_NextButtonClicked(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().NextButtonClicked(*reinterpret_cast<winrt::Microsoft::UI::Xaml::RoutedEventHandler const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall remove_NextButtonClicked(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().NextButtonClicked(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        int32_t __stdcall get_TotalPages(uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<uint32_t>(this->shim().TotalPages());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_TotalPages(uint32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().TotalPages(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_CurrentPage(uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<uint32_t>(this->shim().CurrentPage());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_CurrentPage(uint32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CurrentPage(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IPrinterSettings> : produce_base<D, winrt::VirtualPrinterAppSdk::IPrinterSettings>
    {
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IPrinterSettingsFactory> : produce_base<D, winrt::VirtualPrinterAppSdk::IPrinterSettingsFactory>
    {
        int32_t __stdcall CreateInstance(void* args, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::VirtualPrinterAppSdk::PrinterSettings>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Graphics::Printing::PrintSupport::PrintSupportSettingsActivatedEventArgs const*>(&args)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IUserLaunchMainPage> : produce_base<D, winrt::VirtualPrinterAppSdk::IUserLaunchMainPage>
    {
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl> : produce_base<D, winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl>
    {
        int32_t __stdcall add_WatermarkPreviewTapped(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().WatermarkPreviewTapped(*reinterpret_cast<winrt::Microsoft::UI::Xaml::Input::TappedEventHandler const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall remove_WatermarkPreviewTapped(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().WatermarkPreviewTapped(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        int32_t __stdcall PreviewPage(void* pageWrapper) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PreviewPage(*reinterpret_cast<winrt::XpsUtil::XpsPageWrapper const*>(&pageWrapper));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall StartPreviewRefresh() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().StartPreviewRefresh();
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::VirtualPrinterAppSdk::IWorkflowWatermarkSample> : produce_base<D, winrt::VirtualPrinterAppSdk::IWorkflowWatermarkSample>
    {
    };
}
WINRT_EXPORT namespace winrt::VirtualPrinterAppSdk
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::VirtualPrinterAppSdk::IAppInfo> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IJobActivationMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IMainWindowFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IPreviewPaginationControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IPrinterSettings> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IPrinterSettingsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IUserLaunchMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IWatermarkPreviewControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::IWorkflowWatermarkSample> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::AppInfo> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::JobActivationMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::PreviewPaginationControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::PrinterSettings> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::UserLaunchMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::WatermarkPreviewControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::WorkflowWatermarkSample> : winrt::impl::hash_base {};
    template<> struct hash<winrt::VirtualPrinterAppSdk::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
