// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

void* winrt_make_XpsUtil_XpsSequentialDocument()
{
    return winrt::detach_abi(winrt::make<winrt::XpsUtil::factory_implementation::XpsSequentialDocument>());
}
WINRT_EXPORT namespace winrt::XpsUtil
{
    XpsSequentialDocument::XpsSequentialDocument(Windows::Graphics::Printing::Workflow::PrintWorkflowObjectModelSourceFileContent const& sourceFileContent) :
        XpsSequentialDocument(make<XpsUtil::implementation::XpsSequentialDocument>(sourceFileContent))
    {
    }
}
