// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace PSAAppSdk
{
    [default_interface]
    runtimeclass UserLaunchMainPage : Microsoft.UI.Xaml.Controls.Page
    {
        UserLaunchMainPage();

    }
}
