// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_ApplicationModel_Holographic_1_H
#define WINRT_Windows_ApplicationModel_Holographic_1_H
#include "winrt/impl/Windows.ApplicationModel.Holographic.0.h"
WINRT_EXPORT namespace winrt::Windows::ApplicationModel::Holographic
{
    struct __declspec(empty_bases) IHolographicKeyboard :
        Windows::Foundation::IInspectable,
        impl::consume_t<IHolographicKeyboard>
    {
        IHolographicKeyboard(std::nullptr_t = nullptr) noexcept {}
        IHolographicKeyboard(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IHolographicKeyboard(IHolographicKeyboard const&) noexcept = default;
        IHolographicKeyboard(IHolographicKeyboard&&) noexcept = default;
        IHolographicKeyboard& operator=(IHolographicKeyboard const&) & noexcept = default;
        IHolographicKeyboard& operator=(IHolographicKeyboard&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IHolographicKeyboardStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IHolographicKeyboardStatics>
    {
        IHolographicKeyboardStatics(std::nullptr_t = nullptr) noexcept {}
        IHolographicKeyboardStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IHolographicKeyboardStatics(IHolographicKeyboardStatics const&) noexcept = default;
        IHolographicKeyboardStatics(IHolographicKeyboardStatics&&) noexcept = default;
        IHolographicKeyboardStatics& operator=(IHolographicKeyboardStatics const&) & noexcept = default;
        IHolographicKeyboardStatics& operator=(IHolographicKeyboardStatics&&) & noexcept = default;
    };
}
#endif
