// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Devices_Printers_2_H
#define WINRT_Windows_Devices_Printers_2_H
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.Storage.Streams.1.h"
#include "winrt/impl/Windows.Devices.Printers.1.h"
WINRT_EXPORT namespace winrt::Windows::Devices::Printers
{
    struct __declspec(empty_bases) IppAttributeError : Windows::Devices::Printers::IIppAttributeError
    {
        IppAttributeError(std::nullptr_t) noexcept {}
        IppAttributeError(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppAttributeError(ptr, take_ownership_from_abi) {}
        IppAttributeError(IppAttributeError const&) noexcept = default;
        IppAttributeError(IppAttributeError&&) noexcept = default;
        IppAttributeError& operator=(IppAttributeError const&) & noexcept = default;
        IppAttributeError& operator=(IppAttributeError&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IppAttributeValue : Windows::Devices::Printers::IIppAttributeValue
    {
        IppAttributeValue(std::nullptr_t) noexcept {}
        IppAttributeValue(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppAttributeValue(ptr, take_ownership_from_abi) {}
        IppAttributeValue(IppAttributeValue const&) noexcept = default;
        IppAttributeValue(IppAttributeValue&&) noexcept = default;
        IppAttributeValue& operator=(IppAttributeValue const&) & noexcept = default;
        IppAttributeValue& operator=(IppAttributeValue&&) & noexcept = default;
        static auto CreateUnsupported();
        static auto CreateUnknown();
        static auto CreateNoValue();
        static auto CreateInteger(int32_t value);
        static auto CreateIntegerArray(param::iterable<int32_t> const& values);
        static auto CreateBoolean(bool value);
        static auto CreateBooleanArray(param::iterable<bool> const& values);
        static auto CreateEnum(int32_t value);
        static auto CreateEnumArray(param::iterable<int32_t> const& values);
        static auto CreateOctetString(Windows::Storage::Streams::IBuffer const& value);
        static auto CreateOctetStringArray(param::iterable<Windows::Storage::Streams::IBuffer> const& values);
        static auto CreateDateTime(Windows::Foundation::DateTime const& value);
        static auto CreateDateTimeArray(param::iterable<Windows::Foundation::DateTime> const& values);
        static auto CreateResolution(Windows::Devices::Printers::IppResolution const& value);
        static auto CreateResolutionArray(param::iterable<Windows::Devices::Printers::IppResolution> const& values);
        static auto CreateRangeOfInteger(Windows::Devices::Printers::IppIntegerRange const& value);
        static auto CreateRangeOfIntegerArray(param::iterable<Windows::Devices::Printers::IppIntegerRange> const& values);
        static auto CreateCollection(param::iterable<Windows::Foundation::Collections::IKeyValuePair<hstring, Windows::Devices::Printers::IppAttributeValue>> const& memberAttributes);
        static auto CreateCollectionArray(param::iterable<Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<hstring, Windows::Devices::Printers::IppAttributeValue>>> const& memberAttributesArray);
        static auto CreateTextWithLanguage(Windows::Devices::Printers::IppTextWithLanguage const& value);
        static auto CreateTextWithLanguageArray(param::iterable<Windows::Devices::Printers::IppTextWithLanguage> const& values);
        static auto CreateNameWithLanguage(Windows::Devices::Printers::IppTextWithLanguage const& value);
        static auto CreateNameWithLanguageArray(param::iterable<Windows::Devices::Printers::IppTextWithLanguage> const& values);
        static auto CreateTextWithoutLanguage(param::hstring const& value);
        static auto CreateTextWithoutLanguageArray(param::iterable<hstring> const& values);
        static auto CreateNameWithoutLanguage(param::hstring const& value);
        static auto CreateNameWithoutLanguageArray(param::iterable<hstring> const& values);
        static auto CreateKeyword(param::hstring const& value);
        static auto CreateKeywordArray(param::iterable<hstring> const& values);
        static auto CreateUri(Windows::Foundation::Uri const& value);
        static auto CreateUriArray(param::iterable<Windows::Foundation::Uri> const& values);
        static auto CreateUriSchema(param::hstring const& value);
        static auto CreateUriSchemaArray(param::iterable<hstring> const& values);
        static auto CreateCharset(param::hstring const& value);
        static auto CreateCharsetArray(param::iterable<hstring> const& values);
        static auto CreateNaturalLanguage(param::hstring const& value);
        static auto CreateNaturalLanguageArray(param::iterable<hstring> const& values);
        static auto CreateMimeMedia(param::hstring const& value);
        static auto CreateMimeMediaArray(param::iterable<hstring> const& values);
    };
    struct __declspec(empty_bases) IppIntegerRange : Windows::Devices::Printers::IIppIntegerRange
    {
        IppIntegerRange(std::nullptr_t) noexcept {}
        IppIntegerRange(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppIntegerRange(ptr, take_ownership_from_abi) {}
        IppIntegerRange(int32_t start, int32_t end);
        IppIntegerRange(IppIntegerRange const&) noexcept = default;
        IppIntegerRange(IppIntegerRange&&) noexcept = default;
        IppIntegerRange& operator=(IppIntegerRange const&) & noexcept = default;
        IppIntegerRange& operator=(IppIntegerRange&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IppPrintDevice : Windows::Devices::Printers::IIppPrintDevice,
        impl::require<IppPrintDevice, Windows::Devices::Printers::IIppPrintDevice2, Windows::Devices::Printers::IIppPrintDevice3, Windows::Devices::Printers::IIppPrintDevice4, Windows::Devices::Printers::IIppPrintDevice5>
    {
        IppPrintDevice(std::nullptr_t) noexcept {}
        IppPrintDevice(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppPrintDevice(ptr, take_ownership_from_abi) {}
        IppPrintDevice(IppPrintDevice const&) noexcept = default;
        IppPrintDevice(IppPrintDevice&&) noexcept = default;
        IppPrintDevice& operator=(IppPrintDevice const&) & noexcept = default;
        IppPrintDevice& operator=(IppPrintDevice&&) & noexcept = default;
        static auto GetDeviceSelector();
        static auto FromId(param::hstring const& deviceId);
        static auto FromPrinterName(param::hstring const& printerName);
        static auto IsIppPrinter(param::hstring const& printerName);
    };
    struct __declspec(empty_bases) IppPrintDeviceInstallationResult : Windows::Devices::Printers::IIppPrintDeviceInstallationResult
    {
        IppPrintDeviceInstallationResult(std::nullptr_t) noexcept {}
        IppPrintDeviceInstallationResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppPrintDeviceInstallationResult(ptr, take_ownership_from_abi) {}
        IppPrintDeviceInstallationResult(IppPrintDeviceInstallationResult const&) noexcept = default;
        IppPrintDeviceInstallationResult(IppPrintDeviceInstallationResult&&) noexcept = default;
        IppPrintDeviceInstallationResult& operator=(IppPrintDeviceInstallationResult const&) & noexcept = default;
        IppPrintDeviceInstallationResult& operator=(IppPrintDeviceInstallationResult&&) & noexcept = default;
    };
    struct IppPrintDeviceManager
    {
        IppPrintDeviceManager() = delete;
        static auto CanInstallIppPrintDevice();
        static auto InstallIppPrintDeviceAsync(Windows::Foundation::Uri const& printerUri, param::hstring const& printerName);
    };
    struct __declspec(empty_bases) IppResolution : Windows::Devices::Printers::IIppResolution
    {
        IppResolution(std::nullptr_t) noexcept {}
        IppResolution(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppResolution(ptr, take_ownership_from_abi) {}
        IppResolution(int32_t width, int32_t height, Windows::Devices::Printers::IppResolutionUnit const& unit);
        IppResolution(IppResolution const&) noexcept = default;
        IppResolution(IppResolution&&) noexcept = default;
        IppResolution& operator=(IppResolution const&) & noexcept = default;
        IppResolution& operator=(IppResolution&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IppSetAttributesResult : Windows::Devices::Printers::IIppSetAttributesResult
    {
        IppSetAttributesResult(std::nullptr_t) noexcept {}
        IppSetAttributesResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppSetAttributesResult(ptr, take_ownership_from_abi) {}
        IppSetAttributesResult(IppSetAttributesResult const&) noexcept = default;
        IppSetAttributesResult(IppSetAttributesResult&&) noexcept = default;
        IppSetAttributesResult& operator=(IppSetAttributesResult const&) & noexcept = default;
        IppSetAttributesResult& operator=(IppSetAttributesResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IppTextWithLanguage : Windows::Devices::Printers::IIppTextWithLanguage
    {
        IppTextWithLanguage(std::nullptr_t) noexcept {}
        IppTextWithLanguage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IIppTextWithLanguage(ptr, take_ownership_from_abi) {}
        IppTextWithLanguage(param::hstring const& language, param::hstring const& text);
        IppTextWithLanguage(IppTextWithLanguage const&) noexcept = default;
        IppTextWithLanguage(IppTextWithLanguage&&) noexcept = default;
        IppTextWithLanguage& operator=(IppTextWithLanguage const&) & noexcept = default;
        IppTextWithLanguage& operator=(IppTextWithLanguage&&) & noexcept = default;
    };
    struct __declspec(empty_bases) PageConfigurationSettings : Windows::Devices::Printers::IPageConfigurationSettings
    {
        PageConfigurationSettings(std::nullptr_t) noexcept {}
        PageConfigurationSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IPageConfigurationSettings(ptr, take_ownership_from_abi) {}
        PageConfigurationSettings();
        PageConfigurationSettings(PageConfigurationSettings const&) noexcept = default;
        PageConfigurationSettings(PageConfigurationSettings&&) noexcept = default;
        PageConfigurationSettings& operator=(PageConfigurationSettings const&) & noexcept = default;
        PageConfigurationSettings& operator=(PageConfigurationSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) PdlPassthroughProvider : Windows::Devices::Printers::IPdlPassthroughProvider
    {
        PdlPassthroughProvider(std::nullptr_t) noexcept {}
        PdlPassthroughProvider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IPdlPassthroughProvider(ptr, take_ownership_from_abi) {}
        PdlPassthroughProvider(PdlPassthroughProvider const&) noexcept = default;
        PdlPassthroughProvider(PdlPassthroughProvider&&) noexcept = default;
        PdlPassthroughProvider& operator=(PdlPassthroughProvider const&) & noexcept = default;
        PdlPassthroughProvider& operator=(PdlPassthroughProvider&&) & noexcept = default;
    };
    struct __declspec(empty_bases) PdlPassthroughTarget : Windows::Devices::Printers::IPdlPassthroughTarget,
        impl::require<PdlPassthroughTarget, Windows::Foundation::IClosable>
    {
        PdlPassthroughTarget(std::nullptr_t) noexcept {}
        PdlPassthroughTarget(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IPdlPassthroughTarget(ptr, take_ownership_from_abi) {}
        PdlPassthroughTarget(PdlPassthroughTarget const&) noexcept = default;
        PdlPassthroughTarget(PdlPassthroughTarget&&) noexcept = default;
        PdlPassthroughTarget& operator=(PdlPassthroughTarget const&) & noexcept = default;
        PdlPassthroughTarget& operator=(PdlPassthroughTarget&&) & noexcept = default;
    };
    struct __declspec(empty_bases) Print3DDevice : Windows::Devices::Printers::IPrint3DDevice
    {
        Print3DDevice(std::nullptr_t) noexcept {}
        Print3DDevice(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IPrint3DDevice(ptr, take_ownership_from_abi) {}
        Print3DDevice(Print3DDevice const&) noexcept = default;
        Print3DDevice(Print3DDevice&&) noexcept = default;
        Print3DDevice& operator=(Print3DDevice const&) & noexcept = default;
        Print3DDevice& operator=(Print3DDevice&&) & noexcept = default;
        static auto FromIdAsync(param::hstring const& deviceId);
        static auto GetDeviceSelector();
    };
    struct __declspec(empty_bases) PrintSchema : Windows::Devices::Printers::IPrintSchema
    {
        PrintSchema(std::nullptr_t) noexcept {}
        PrintSchema(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IPrintSchema(ptr, take_ownership_from_abi) {}
        PrintSchema(PrintSchema const&) noexcept = default;
        PrintSchema(PrintSchema&&) noexcept = default;
        PrintSchema& operator=(PrintSchema const&) & noexcept = default;
        PrintSchema& operator=(PrintSchema&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ReplaceDevicePropertiesResult : Windows::Devices::Printers::IReplaceDevicePropertiesResult
    {
        ReplaceDevicePropertiesResult(std::nullptr_t) noexcept {}
        ReplaceDevicePropertiesResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IReplaceDevicePropertiesResult(ptr, take_ownership_from_abi) {}
        ReplaceDevicePropertiesResult(ReplaceDevicePropertiesResult const&) noexcept = default;
        ReplaceDevicePropertiesResult(ReplaceDevicePropertiesResult&&) noexcept = default;
        ReplaceDevicePropertiesResult& operator=(ReplaceDevicePropertiesResult const&) & noexcept = default;
        ReplaceDevicePropertiesResult& operator=(ReplaceDevicePropertiesResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) VirtualPrinterInstallationParameters : Windows::Devices::Printers::IVirtualPrinterInstallationParameters
    {
        VirtualPrinterInstallationParameters(std::nullptr_t) noexcept {}
        VirtualPrinterInstallationParameters(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IVirtualPrinterInstallationParameters(ptr, take_ownership_from_abi) {}
        VirtualPrinterInstallationParameters();
        VirtualPrinterInstallationParameters(VirtualPrinterInstallationParameters const&) noexcept = default;
        VirtualPrinterInstallationParameters(VirtualPrinterInstallationParameters&&) noexcept = default;
        VirtualPrinterInstallationParameters& operator=(VirtualPrinterInstallationParameters const&) & noexcept = default;
        VirtualPrinterInstallationParameters& operator=(VirtualPrinterInstallationParameters&&) & noexcept = default;
    };
    struct __declspec(empty_bases) VirtualPrinterInstallationResult : Windows::Devices::Printers::IVirtualPrinterInstallationResult
    {
        VirtualPrinterInstallationResult(std::nullptr_t) noexcept {}
        VirtualPrinterInstallationResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IVirtualPrinterInstallationResult(ptr, take_ownership_from_abi) {}
        VirtualPrinterInstallationResult(VirtualPrinterInstallationResult const&) noexcept = default;
        VirtualPrinterInstallationResult(VirtualPrinterInstallationResult&&) noexcept = default;
        VirtualPrinterInstallationResult& operator=(VirtualPrinterInstallationResult const&) & noexcept = default;
        VirtualPrinterInstallationResult& operator=(VirtualPrinterInstallationResult&&) & noexcept = default;
    };
    struct VirtualPrinterManager
    {
        VirtualPrinterManager() = delete;
        static auto InstallVirtualPrinterAsync(Windows::Devices::Printers::VirtualPrinterInstallationParameters const& parameters);
        static auto InstallVirtualPrinterAsync(Windows::Devices::Printers::VirtualPrinterInstallationParameters const& parameters, param::hstring const& appPackageFamilyName);
        static auto InstallVirtualPrinterForAllUsersAsync(Windows::Devices::Printers::VirtualPrinterInstallationParameters const& parameters);
        static auto InstallVirtualPrinterForAllUsersAsync(Windows::Devices::Printers::VirtualPrinterInstallationParameters const& parameters, param::hstring const& appPackageFamilyName);
        static auto FindAllVirtualPrinters();
        static auto FindAllVirtualPrinters(param::hstring const& appPackageFamilyName);
        static auto RemoveVirtualPrinterAsync(param::hstring const& printerName);
        static auto RemoveVirtualPrinterForAllUsersAsync(param::hstring const& printerName);
    };
    struct __declspec(empty_bases) VirtualPrinterSupportedFormat : Windows::Devices::Printers::IVirtualPrinterSupportedFormat
    {
        VirtualPrinterSupportedFormat(std::nullptr_t) noexcept {}
        VirtualPrinterSupportedFormat(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Devices::Printers::IVirtualPrinterSupportedFormat(ptr, take_ownership_from_abi) {}
        VirtualPrinterSupportedFormat(param::hstring const& contentType, param::hstring const& maxSupportedVersion);
        VirtualPrinterSupportedFormat(VirtualPrinterSupportedFormat const&) noexcept = default;
        VirtualPrinterSupportedFormat(VirtualPrinterSupportedFormat&&) noexcept = default;
        VirtualPrinterSupportedFormat& operator=(VirtualPrinterSupportedFormat const&) & noexcept = default;
        VirtualPrinterSupportedFormat& operator=(VirtualPrinterSupportedFormat&&) & noexcept = default;
    };
}
#endif
