// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Security_Authorization_AppCapabilityAccess_1_H
#define WINRT_Windows_Security_Authorization_AppCapabilityAccess_1_H
#include "winrt/impl/Windows.Security.Authorization.AppCapabilityAccess.0.h"
WINRT_EXPORT namespace winrt::Windows::Security::Authorization::AppCapabilityAccess
{
    struct __declspec(empty_bases) IAppCapability :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCapability>
    {
        IAppCapability(std::nullptr_t = nullptr) noexcept {}
        IAppCapability(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCapability(IAppCapability const&) noexcept = default;
        IAppCapability(IAppCapability&&) noexcept = default;
        IAppCapability& operator=(IAppCapability const&) & noexcept = default;
        IAppCapability& operator=(IAppCapability&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCapability2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCapability2>
    {
        IAppCapability2(std::nullptr_t = nullptr) noexcept {}
        IAppCapability2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCapability2(IAppCapability2 const&) noexcept = default;
        IAppCapability2(IAppCapability2&&) noexcept = default;
        IAppCapability2& operator=(IAppCapability2 const&) & noexcept = default;
        IAppCapability2& operator=(IAppCapability2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCapabilityAccessChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCapabilityAccessChangedEventArgs>
    {
        IAppCapabilityAccessChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppCapabilityAccessChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCapabilityAccessChangedEventArgs(IAppCapabilityAccessChangedEventArgs const&) noexcept = default;
        IAppCapabilityAccessChangedEventArgs(IAppCapabilityAccessChangedEventArgs&&) noexcept = default;
        IAppCapabilityAccessChangedEventArgs& operator=(IAppCapabilityAccessChangedEventArgs const&) & noexcept = default;
        IAppCapabilityAccessChangedEventArgs& operator=(IAppCapabilityAccessChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCapabilityStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCapabilityStatics>
    {
        IAppCapabilityStatics(std::nullptr_t = nullptr) noexcept {}
        IAppCapabilityStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCapabilityStatics(IAppCapabilityStatics const&) noexcept = default;
        IAppCapabilityStatics(IAppCapabilityStatics&&) noexcept = default;
        IAppCapabilityStatics& operator=(IAppCapabilityStatics const&) & noexcept = default;
        IAppCapabilityStatics& operator=(IAppCapabilityStatics&&) & noexcept = default;
    };
}
#endif
