// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Foundation_1_H
#define WINRT_Windows_Foundation_1_H
#include "winrt/impl/Windows.Foundation.Collections.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct __declspec(empty_bases) IAsyncAction :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAsyncAction>,
        impl::require<Windows::Foundation::IAsyncAction, Windows::Foundation::IAsyncInfo>
    {
        IAsyncAction(std::nullptr_t = nullptr) noexcept {}
        IAsyncAction(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAsyncAction(IAsyncAction const&) noexcept = default;
        IAsyncAction(IAsyncAction&&) noexcept = default;
        IAsyncAction& operator=(IAsyncAction const&) & noexcept = default;
        IAsyncAction& operator=(IAsyncAction&&) & noexcept = default;
    };
    template <typename TProgress>
    struct __declspec(empty_bases) IAsyncActionWithProgress :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::IAsyncActionWithProgress<TProgress>>,
        impl::require<Windows::Foundation::IAsyncActionWithProgress<TProgress>, Windows::Foundation::IAsyncInfo>
    {
        static_assert(impl::has_category_v<TProgress>, "TProgress must be WinRT type.");
        IAsyncActionWithProgress(std::nullptr_t = nullptr) noexcept {}
        IAsyncActionWithProgress(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAsyncActionWithProgress(IAsyncActionWithProgress const&) noexcept = default;
        IAsyncActionWithProgress(IAsyncActionWithProgress&&) noexcept = default;
        IAsyncActionWithProgress& operator=(IAsyncActionWithProgress const&) & noexcept = default;
        IAsyncActionWithProgress& operator=(IAsyncActionWithProgress&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAsyncInfo :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAsyncInfo>
    {
        IAsyncInfo(std::nullptr_t = nullptr) noexcept {}
        IAsyncInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAsyncInfo(IAsyncInfo const&) noexcept = default;
        IAsyncInfo(IAsyncInfo&&) noexcept = default;
        IAsyncInfo& operator=(IAsyncInfo const&) & noexcept = default;
        IAsyncInfo& operator=(IAsyncInfo&&) & noexcept = default;
    };
    template <typename TResult, typename TProgress>
    struct __declspec(empty_bases) IAsyncOperationWithProgress :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::IAsyncOperationWithProgress<TResult, TProgress>>,
        impl::require<Windows::Foundation::IAsyncOperationWithProgress<TResult, TProgress>, Windows::Foundation::IAsyncInfo>
    {
        static_assert(impl::has_category_v<TResult>, "TResult must be WinRT type.");
        static_assert(impl::has_category_v<TProgress>, "TProgress must be WinRT type.");
        IAsyncOperationWithProgress(std::nullptr_t = nullptr) noexcept {}
        IAsyncOperationWithProgress(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAsyncOperationWithProgress(IAsyncOperationWithProgress const&) noexcept = default;
        IAsyncOperationWithProgress(IAsyncOperationWithProgress&&) noexcept = default;
        IAsyncOperationWithProgress& operator=(IAsyncOperationWithProgress const&) & noexcept = default;
        IAsyncOperationWithProgress& operator=(IAsyncOperationWithProgress&&) & noexcept = default;
    };
    template <typename TResult>
    struct __declspec(empty_bases) IAsyncOperation :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::IAsyncOperation<TResult>>,
        impl::require<Windows::Foundation::IAsyncOperation<TResult>, Windows::Foundation::IAsyncInfo>
    {
        static_assert(impl::has_category_v<TResult>, "TResult must be WinRT type.");
        IAsyncOperation(std::nullptr_t = nullptr) noexcept {}
        IAsyncOperation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAsyncOperation(IAsyncOperation const&) noexcept = default;
        IAsyncOperation(IAsyncOperation&&) noexcept = default;
        IAsyncOperation& operator=(IAsyncOperation const&) & noexcept = default;
        IAsyncOperation& operator=(IAsyncOperation&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IClosable :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClosable>
    {
        IClosable(std::nullptr_t = nullptr) noexcept {}
        IClosable(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IClosable(IClosable const&) noexcept = default;
        IClosable(IClosable&&) noexcept = default;
        IClosable& operator=(IClosable const&) & noexcept = default;
        IClosable& operator=(IClosable&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IDeferral :
        Windows::Foundation::IInspectable,
        impl::consume_t<IDeferral>,
        impl::require<Windows::Foundation::IDeferral, Windows::Foundation::IClosable>
    {
        IDeferral(std::nullptr_t = nullptr) noexcept {}
        IDeferral(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IDeferral(IDeferral const&) noexcept = default;
        IDeferral(IDeferral&&) noexcept = default;
        IDeferral& operator=(IDeferral const&) & noexcept = default;
        IDeferral& operator=(IDeferral&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IDeferralFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IDeferralFactory>
    {
        IDeferralFactory(std::nullptr_t = nullptr) noexcept {}
        IDeferralFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IDeferralFactory(IDeferralFactory const&) noexcept = default;
        IDeferralFactory(IDeferralFactory&&) noexcept = default;
        IDeferralFactory& operator=(IDeferralFactory const&) & noexcept = default;
        IDeferralFactory& operator=(IDeferralFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGetActivationFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGetActivationFactory>
    {
        IGetActivationFactory(std::nullptr_t = nullptr) noexcept {}
        IGetActivationFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGetActivationFactory(IGetActivationFactory const&) noexcept = default;
        IGetActivationFactory(IGetActivationFactory&&) noexcept = default;
        IGetActivationFactory& operator=(IGetActivationFactory const&) & noexcept = default;
        IGetActivationFactory& operator=(IGetActivationFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGuidHelperStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGuidHelperStatics>
    {
        IGuidHelperStatics(std::nullptr_t = nullptr) noexcept {}
        IGuidHelperStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGuidHelperStatics(IGuidHelperStatics const&) noexcept = default;
        IGuidHelperStatics(IGuidHelperStatics&&) noexcept = default;
        IGuidHelperStatics& operator=(IGuidHelperStatics const&) & noexcept = default;
        IGuidHelperStatics& operator=(IGuidHelperStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMemoryBuffer :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMemoryBuffer>,
        impl::require<Windows::Foundation::IMemoryBuffer, Windows::Foundation::IClosable>
    {
        IMemoryBuffer(std::nullptr_t = nullptr) noexcept {}
        IMemoryBuffer(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMemoryBuffer(IMemoryBuffer const&) noexcept = default;
        IMemoryBuffer(IMemoryBuffer&&) noexcept = default;
        IMemoryBuffer& operator=(IMemoryBuffer const&) & noexcept = default;
        IMemoryBuffer& operator=(IMemoryBuffer&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMemoryBufferFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMemoryBufferFactory>
    {
        IMemoryBufferFactory(std::nullptr_t = nullptr) noexcept {}
        IMemoryBufferFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMemoryBufferFactory(IMemoryBufferFactory const&) noexcept = default;
        IMemoryBufferFactory(IMemoryBufferFactory&&) noexcept = default;
        IMemoryBufferFactory& operator=(IMemoryBufferFactory const&) & noexcept = default;
        IMemoryBufferFactory& operator=(IMemoryBufferFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMemoryBufferReference :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMemoryBufferReference>,
        impl::require<Windows::Foundation::IMemoryBufferReference, Windows::Foundation::IClosable>
    {
        IMemoryBufferReference(std::nullptr_t = nullptr) noexcept {}
        IMemoryBufferReference(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMemoryBufferReference(IMemoryBufferReference const&) noexcept = default;
        IMemoryBufferReference(IMemoryBufferReference&&) noexcept = default;
        IMemoryBufferReference& operator=(IMemoryBufferReference const&) & noexcept = default;
        IMemoryBufferReference& operator=(IMemoryBufferReference&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPropertyValue :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPropertyValue>
    {
        IPropertyValue(std::nullptr_t = nullptr) noexcept {}
        IPropertyValue(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPropertyValue(IPropertyValue const&) noexcept = default;
        IPropertyValue(IPropertyValue&&) noexcept = default;
        IPropertyValue& operator=(IPropertyValue const&) & noexcept = default;
        IPropertyValue& operator=(IPropertyValue&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPropertyValueStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPropertyValueStatics>
    {
        IPropertyValueStatics(std::nullptr_t = nullptr) noexcept {}
        IPropertyValueStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPropertyValueStatics(IPropertyValueStatics const&) noexcept = default;
        IPropertyValueStatics(IPropertyValueStatics&&) noexcept = default;
        IPropertyValueStatics& operator=(IPropertyValueStatics const&) & noexcept = default;
        IPropertyValueStatics& operator=(IPropertyValueStatics&&) & noexcept = default;
    };
    template <typename T>
    struct __declspec(empty_bases) IReferenceArray :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::IReferenceArray<T>>,
        impl::require<Windows::Foundation::IReferenceArray<T>, Windows::Foundation::IPropertyValue>
    {
        static_assert(impl::has_category_v<T>, "T must be WinRT type.");
        IReferenceArray(std::nullptr_t = nullptr) noexcept {}
        IReferenceArray(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IReferenceArray(IReferenceArray const&) noexcept = default;
        IReferenceArray(IReferenceArray&&) noexcept = default;
        IReferenceArray& operator=(IReferenceArray const&) & noexcept = default;
        IReferenceArray& operator=(IReferenceArray&&) & noexcept = default;
    };
    template <typename T>
    struct __declspec(empty_bases) IReference :
        Windows::Foundation::IInspectable,
        impl::consume_t<Windows::Foundation::IReference<T>>,
        impl::require<Windows::Foundation::IReference<T>, Windows::Foundation::IPropertyValue>
    {
        static_assert(impl::has_category_v<T>, "T must be WinRT type.");
        IReference(std::nullptr_t = nullptr) noexcept {}
        IReference(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IReference(IReference const&) noexcept = default;
        IReference(IReference&&) noexcept = default;
        IReference& operator=(IReference const&) & noexcept = default;
        IReference& operator=(IReference&&) & noexcept = default;
        IReference(T const& value) : IReference<T>(impl::reference_traits<T>::make(value))
        {
        }

    private:

        IReference<T>(IInspectable const& value) : IReference<T>(value.as<IReference<T>>())
        {
        }
    };
    struct __declspec(empty_bases) IStringable :
        Windows::Foundation::IInspectable,
        impl::consume_t<IStringable>
    {
        IStringable(std::nullptr_t = nullptr) noexcept {}
        IStringable(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IStringable(IStringable const&) noexcept = default;
        IStringable(IStringable&&) noexcept = default;
        IStringable& operator=(IStringable const&) & noexcept = default;
        IStringable& operator=(IStringable&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IUriEscapeStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IUriEscapeStatics>
    {
        IUriEscapeStatics(std::nullptr_t = nullptr) noexcept {}
        IUriEscapeStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IUriEscapeStatics(IUriEscapeStatics const&) noexcept = default;
        IUriEscapeStatics(IUriEscapeStatics&&) noexcept = default;
        IUriEscapeStatics& operator=(IUriEscapeStatics const&) & noexcept = default;
        IUriEscapeStatics& operator=(IUriEscapeStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IUriRuntimeClass :
        Windows::Foundation::IInspectable,
        impl::consume_t<IUriRuntimeClass>
    {
        IUriRuntimeClass(std::nullptr_t = nullptr) noexcept {}
        IUriRuntimeClass(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IUriRuntimeClass(IUriRuntimeClass const&) noexcept = default;
        IUriRuntimeClass(IUriRuntimeClass&&) noexcept = default;
        IUriRuntimeClass& operator=(IUriRuntimeClass const&) & noexcept = default;
        IUriRuntimeClass& operator=(IUriRuntimeClass&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IUriRuntimeClassFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IUriRuntimeClassFactory>
    {
        IUriRuntimeClassFactory(std::nullptr_t = nullptr) noexcept {}
        IUriRuntimeClassFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IUriRuntimeClassFactory(IUriRuntimeClassFactory const&) noexcept = default;
        IUriRuntimeClassFactory(IUriRuntimeClassFactory&&) noexcept = default;
        IUriRuntimeClassFactory& operator=(IUriRuntimeClassFactory const&) & noexcept = default;
        IUriRuntimeClassFactory& operator=(IUriRuntimeClassFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IUriRuntimeClassWithAbsoluteCanonicalUri :
        Windows::Foundation::IInspectable,
        impl::consume_t<IUriRuntimeClassWithAbsoluteCanonicalUri>
    {
        IUriRuntimeClassWithAbsoluteCanonicalUri(std::nullptr_t = nullptr) noexcept {}
        IUriRuntimeClassWithAbsoluteCanonicalUri(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IUriRuntimeClassWithAbsoluteCanonicalUri(IUriRuntimeClassWithAbsoluteCanonicalUri const&) noexcept = default;
        IUriRuntimeClassWithAbsoluteCanonicalUri(IUriRuntimeClassWithAbsoluteCanonicalUri&&) noexcept = default;
        IUriRuntimeClassWithAbsoluteCanonicalUri& operator=(IUriRuntimeClassWithAbsoluteCanonicalUri const&) & noexcept = default;
        IUriRuntimeClassWithAbsoluteCanonicalUri& operator=(IUriRuntimeClassWithAbsoluteCanonicalUri&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWwwFormUrlDecoderEntry :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWwwFormUrlDecoderEntry>
    {
        IWwwFormUrlDecoderEntry(std::nullptr_t = nullptr) noexcept {}
        IWwwFormUrlDecoderEntry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWwwFormUrlDecoderEntry(IWwwFormUrlDecoderEntry const&) noexcept = default;
        IWwwFormUrlDecoderEntry(IWwwFormUrlDecoderEntry&&) noexcept = default;
        IWwwFormUrlDecoderEntry& operator=(IWwwFormUrlDecoderEntry const&) & noexcept = default;
        IWwwFormUrlDecoderEntry& operator=(IWwwFormUrlDecoderEntry&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWwwFormUrlDecoderRuntimeClass :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWwwFormUrlDecoderRuntimeClass>,
        impl::require<Windows::Foundation::IWwwFormUrlDecoderRuntimeClass, Windows::Foundation::Collections::IIterable<Windows::Foundation::IWwwFormUrlDecoderEntry>, Windows::Foundation::Collections::IVectorView<Windows::Foundation::IWwwFormUrlDecoderEntry>>
    {
        IWwwFormUrlDecoderRuntimeClass(std::nullptr_t = nullptr) noexcept {}
        IWwwFormUrlDecoderRuntimeClass(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWwwFormUrlDecoderRuntimeClass(IWwwFormUrlDecoderRuntimeClass const&) noexcept = default;
        IWwwFormUrlDecoderRuntimeClass(IWwwFormUrlDecoderRuntimeClass&&) noexcept = default;
        IWwwFormUrlDecoderRuntimeClass& operator=(IWwwFormUrlDecoderRuntimeClass const&) & noexcept = default;
        IWwwFormUrlDecoderRuntimeClass& operator=(IWwwFormUrlDecoderRuntimeClass&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IWwwFormUrlDecoderRuntimeClassFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IWwwFormUrlDecoderRuntimeClassFactory>
    {
        IWwwFormUrlDecoderRuntimeClassFactory(std::nullptr_t = nullptr) noexcept {}
        IWwwFormUrlDecoderRuntimeClassFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IWwwFormUrlDecoderRuntimeClassFactory(IWwwFormUrlDecoderRuntimeClassFactory const&) noexcept = default;
        IWwwFormUrlDecoderRuntimeClassFactory(IWwwFormUrlDecoderRuntimeClassFactory&&) noexcept = default;
        IWwwFormUrlDecoderRuntimeClassFactory& operator=(IWwwFormUrlDecoderRuntimeClassFactory const&) & noexcept = default;
        IWwwFormUrlDecoderRuntimeClassFactory& operator=(IWwwFormUrlDecoderRuntimeClassFactory&&) & noexcept = default;
    };
}
#endif
