// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_UI_UIAutomation_Core_1_H
#define WINRT_Windows_UI_UIAutomation_Core_1_H
#include "winrt/impl/Windows.UI.UIAutomation.Core.0.h"
WINRT_EXPORT namespace winrt::Windows::UI::UIAutomation::Core
{
    struct __declspec(empty_bases) IAutomationRemoteOperationResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutomationRemoteOperationResult>
    {
        IAutomationRemoteOperationResult(std::nullptr_t = nullptr) noexcept {}
        IAutomationRemoteOperationResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAutomationRemoteOperationResult(IAutomationRemoteOperationResult const&) noexcept = default;
        IAutomationRemoteOperationResult(IAutomationRemoteOperationResult&&) noexcept = default;
        IAutomationRemoteOperationResult& operator=(IAutomationRemoteOperationResult const&) & noexcept = default;
        IAutomationRemoteOperationResult& operator=(IAutomationRemoteOperationResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICoreAutomationConnectionBoundObjectProvider :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAutomationConnectionBoundObjectProvider>
    {
        ICoreAutomationConnectionBoundObjectProvider(std::nullptr_t = nullptr) noexcept {}
        ICoreAutomationConnectionBoundObjectProvider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICoreAutomationConnectionBoundObjectProvider(ICoreAutomationConnectionBoundObjectProvider const&) noexcept = default;
        ICoreAutomationConnectionBoundObjectProvider(ICoreAutomationConnectionBoundObjectProvider&&) noexcept = default;
        ICoreAutomationConnectionBoundObjectProvider& operator=(ICoreAutomationConnectionBoundObjectProvider const&) & noexcept = default;
        ICoreAutomationConnectionBoundObjectProvider& operator=(ICoreAutomationConnectionBoundObjectProvider&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICoreAutomationRegistrarStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAutomationRegistrarStatics>
    {
        ICoreAutomationRegistrarStatics(std::nullptr_t = nullptr) noexcept {}
        ICoreAutomationRegistrarStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICoreAutomationRegistrarStatics(ICoreAutomationRegistrarStatics const&) noexcept = default;
        ICoreAutomationRegistrarStatics(ICoreAutomationRegistrarStatics&&) noexcept = default;
        ICoreAutomationRegistrarStatics& operator=(ICoreAutomationRegistrarStatics const&) & noexcept = default;
        ICoreAutomationRegistrarStatics& operator=(ICoreAutomationRegistrarStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICoreAutomationRemoteOperation :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAutomationRemoteOperation>
    {
        ICoreAutomationRemoteOperation(std::nullptr_t = nullptr) noexcept {}
        ICoreAutomationRemoteOperation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICoreAutomationRemoteOperation(ICoreAutomationRemoteOperation const&) noexcept = default;
        ICoreAutomationRemoteOperation(ICoreAutomationRemoteOperation&&) noexcept = default;
        ICoreAutomationRemoteOperation& operator=(ICoreAutomationRemoteOperation const&) & noexcept = default;
        ICoreAutomationRemoteOperation& operator=(ICoreAutomationRemoteOperation&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICoreAutomationRemoteOperation2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAutomationRemoteOperation2>
    {
        ICoreAutomationRemoteOperation2(std::nullptr_t = nullptr) noexcept {}
        ICoreAutomationRemoteOperation2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICoreAutomationRemoteOperation2(ICoreAutomationRemoteOperation2 const&) noexcept = default;
        ICoreAutomationRemoteOperation2(ICoreAutomationRemoteOperation2&&) noexcept = default;
        ICoreAutomationRemoteOperation2& operator=(ICoreAutomationRemoteOperation2 const&) & noexcept = default;
        ICoreAutomationRemoteOperation2& operator=(ICoreAutomationRemoteOperation2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICoreAutomationRemoteOperationContext :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAutomationRemoteOperationContext>
    {
        ICoreAutomationRemoteOperationContext(std::nullptr_t = nullptr) noexcept {}
        ICoreAutomationRemoteOperationContext(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICoreAutomationRemoteOperationContext(ICoreAutomationRemoteOperationContext const&) noexcept = default;
        ICoreAutomationRemoteOperationContext(ICoreAutomationRemoteOperationContext&&) noexcept = default;
        ICoreAutomationRemoteOperationContext& operator=(ICoreAutomationRemoteOperationContext const&) & noexcept = default;
        ICoreAutomationRemoteOperationContext& operator=(ICoreAutomationRemoteOperationContext&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICoreAutomationRemoteOperationExtensionProvider :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAutomationRemoteOperationExtensionProvider>
    {
        ICoreAutomationRemoteOperationExtensionProvider(std::nullptr_t = nullptr) noexcept {}
        ICoreAutomationRemoteOperationExtensionProvider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICoreAutomationRemoteOperationExtensionProvider(ICoreAutomationRemoteOperationExtensionProvider const&) noexcept = default;
        ICoreAutomationRemoteOperationExtensionProvider(ICoreAutomationRemoteOperationExtensionProvider&&) noexcept = default;
        ICoreAutomationRemoteOperationExtensionProvider& operator=(ICoreAutomationRemoteOperationExtensionProvider const&) & noexcept = default;
        ICoreAutomationRemoteOperationExtensionProvider& operator=(ICoreAutomationRemoteOperationExtensionProvider&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemoteAutomationClientSession :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemoteAutomationClientSession>
    {
        IRemoteAutomationClientSession(std::nullptr_t = nullptr) noexcept {}
        IRemoteAutomationClientSession(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemoteAutomationClientSession(IRemoteAutomationClientSession const&) noexcept = default;
        IRemoteAutomationClientSession(IRemoteAutomationClientSession&&) noexcept = default;
        IRemoteAutomationClientSession& operator=(IRemoteAutomationClientSession const&) & noexcept = default;
        IRemoteAutomationClientSession& operator=(IRemoteAutomationClientSession&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemoteAutomationClientSessionFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemoteAutomationClientSessionFactory>
    {
        IRemoteAutomationClientSessionFactory(std::nullptr_t = nullptr) noexcept {}
        IRemoteAutomationClientSessionFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemoteAutomationClientSessionFactory(IRemoteAutomationClientSessionFactory const&) noexcept = default;
        IRemoteAutomationClientSessionFactory(IRemoteAutomationClientSessionFactory&&) noexcept = default;
        IRemoteAutomationClientSessionFactory& operator=(IRemoteAutomationClientSessionFactory const&) & noexcept = default;
        IRemoteAutomationClientSessionFactory& operator=(IRemoteAutomationClientSessionFactory&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemoteAutomationConnectionRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemoteAutomationConnectionRequestedEventArgs>
    {
        IRemoteAutomationConnectionRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IRemoteAutomationConnectionRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemoteAutomationConnectionRequestedEventArgs(IRemoteAutomationConnectionRequestedEventArgs const&) noexcept = default;
        IRemoteAutomationConnectionRequestedEventArgs(IRemoteAutomationConnectionRequestedEventArgs&&) noexcept = default;
        IRemoteAutomationConnectionRequestedEventArgs& operator=(IRemoteAutomationConnectionRequestedEventArgs const&) & noexcept = default;
        IRemoteAutomationConnectionRequestedEventArgs& operator=(IRemoteAutomationConnectionRequestedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemoteAutomationDisconnectedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemoteAutomationDisconnectedEventArgs>
    {
        IRemoteAutomationDisconnectedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IRemoteAutomationDisconnectedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemoteAutomationDisconnectedEventArgs(IRemoteAutomationDisconnectedEventArgs const&) noexcept = default;
        IRemoteAutomationDisconnectedEventArgs(IRemoteAutomationDisconnectedEventArgs&&) noexcept = default;
        IRemoteAutomationDisconnectedEventArgs& operator=(IRemoteAutomationDisconnectedEventArgs const&) & noexcept = default;
        IRemoteAutomationDisconnectedEventArgs& operator=(IRemoteAutomationDisconnectedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemoteAutomationServerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemoteAutomationServerStatics>
    {
        IRemoteAutomationServerStatics(std::nullptr_t = nullptr) noexcept {}
        IRemoteAutomationServerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemoteAutomationServerStatics(IRemoteAutomationServerStatics const&) noexcept = default;
        IRemoteAutomationServerStatics(IRemoteAutomationServerStatics&&) noexcept = default;
        IRemoteAutomationServerStatics& operator=(IRemoteAutomationServerStatics const&) & noexcept = default;
        IRemoteAutomationServerStatics& operator=(IRemoteAutomationServerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IRemoteAutomationWindow :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRemoteAutomationWindow>
    {
        IRemoteAutomationWindow(std::nullptr_t = nullptr) noexcept {}
        IRemoteAutomationWindow(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IRemoteAutomationWindow(IRemoteAutomationWindow const&) noexcept = default;
        IRemoteAutomationWindow(IRemoteAutomationWindow&&) noexcept = default;
        IRemoteAutomationWindow& operator=(IRemoteAutomationWindow const&) & noexcept = default;
        IRemoteAutomationWindow& operator=(IRemoteAutomationWindow&&) & noexcept = default;
    };
}
#endif
