// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Media_ClosedCaptioning_1_H
#define WINRT_Windows_Media_ClosedCaptioning_1_H
#include "winrt/impl/Windows.Media.ClosedCaptioning.0.h"
WINRT_EXPORT namespace winrt::Windows::Media::ClosedCaptioning
{
    struct __declspec(empty_bases) IClosedCaptionPropertiesStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClosedCaptionPropertiesStatics>
    {
        IClosedCaptionPropertiesStatics(std::nullptr_t = nullptr) noexcept {}
        IClosedCaptionPropertiesStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IClosedCaptionPropertiesStatics(IClosedCaptionPropertiesStatics const&) noexcept = default;
        IClosedCaptionPropertiesStatics(IClosedCaptionPropertiesStatics&&) noexcept = default;
        IClosedCaptionPropertiesStatics& operator=(IClosedCaptionPropertiesStatics const&) & noexcept = default;
        IClosedCaptionPropertiesStatics& operator=(IClosedCaptionPropertiesStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IClosedCaptionPropertiesStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClosedCaptionPropertiesStatics2>
    {
        IClosedCaptionPropertiesStatics2(std::nullptr_t = nullptr) noexcept {}
        IClosedCaptionPropertiesStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IClosedCaptionPropertiesStatics2(IClosedCaptionPropertiesStatics2 const&) noexcept = default;
        IClosedCaptionPropertiesStatics2(IClosedCaptionPropertiesStatics2&&) noexcept = default;
        IClosedCaptionPropertiesStatics2& operator=(IClosedCaptionPropertiesStatics2 const&) & noexcept = default;
        IClosedCaptionPropertiesStatics2& operator=(IClosedCaptionPropertiesStatics2&&) & noexcept = default;
    };
}
#endif
