// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210122.3

#ifndef WINRT_Windows_Storage_Provider_2_H
#define WINRT_Windows_Storage_Provider_2_H
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.Storage.1.h"
#include "winrt/impl/Windows.Storage.Provider.1.h"
WINRT_EXPORT namespace winrt::Windows::Storage::Provider
{
    struct StorageProviderKnownFolderSyncRequestedHandler : Windows::Foundation::IUnknown
    {
        StorageProviderKnownFolderSyncRequestedHandler(std::nullptr_t = nullptr) noexcept {}
        StorageProviderKnownFolderSyncRequestedHandler(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IUnknown(ptr, take_ownership_from_abi) {}
        StorageProviderKnownFolderSyncRequestedHandler(StorageProviderKnownFolderSyncRequestedHandler const&) noexcept = default;
        StorageProviderKnownFolderSyncRequestedHandler(StorageProviderKnownFolderSyncRequestedHandler&&) noexcept = default;
        StorageProviderKnownFolderSyncRequestedHandler& operator=(StorageProviderKnownFolderSyncRequestedHandler const&) & noexcept = default;
        StorageProviderKnownFolderSyncRequestedHandler& operator=(StorageProviderKnownFolderSyncRequestedHandler&&) & noexcept = default;
        template <typename L> StorageProviderKnownFolderSyncRequestedHandler(L lambda);
        template <typename F> StorageProviderKnownFolderSyncRequestedHandler(F* function);
        template <typename O, typename M> StorageProviderKnownFolderSyncRequestedHandler(O* object, M method);
        template <typename O, typename M> StorageProviderKnownFolderSyncRequestedHandler(com_ptr<O>&& object, M method);
        template <typename O, typename M> StorageProviderKnownFolderSyncRequestedHandler(weak_ref<O>&& object, M method);
        auto operator()(Windows::Storage::Provider::StorageProviderKnownFolderSyncRequestArgs const& args) const;
    };
    struct CachedFileUpdater
    {
        CachedFileUpdater() = delete;
        static auto SetUpdateInformation(Windows::Storage::IStorageFile const& file, param::hstring const& contentId, Windows::Storage::Provider::ReadActivationMode const& readMode, Windows::Storage::Provider::WriteActivationMode const& writeMode, Windows::Storage::Provider::CachedFileOptions const& options);
    };
    struct __declspec(empty_bases) CachedFileUpdaterUI : Windows::Storage::Provider::ICachedFileUpdaterUI,
        impl::require<CachedFileUpdaterUI, Windows::Storage::Provider::ICachedFileUpdaterUI2>
    {
        CachedFileUpdaterUI(std::nullptr_t) noexcept {}
        CachedFileUpdaterUI(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::ICachedFileUpdaterUI(ptr, take_ownership_from_abi) {}
        CachedFileUpdaterUI(CachedFileUpdaterUI const&) noexcept = default;
        CachedFileUpdaterUI(CachedFileUpdaterUI&&) noexcept = default;
        CachedFileUpdaterUI& operator=(CachedFileUpdaterUI const&) & noexcept = default;
        CachedFileUpdaterUI& operator=(CachedFileUpdaterUI&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileUpdateRequest : Windows::Storage::Provider::IFileUpdateRequest,
        impl::require<FileUpdateRequest, Windows::Storage::Provider::IFileUpdateRequest2>
    {
        FileUpdateRequest(std::nullptr_t) noexcept {}
        FileUpdateRequest(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IFileUpdateRequest(ptr, take_ownership_from_abi) {}
        FileUpdateRequest(FileUpdateRequest const&) noexcept = default;
        FileUpdateRequest(FileUpdateRequest&&) noexcept = default;
        FileUpdateRequest& operator=(FileUpdateRequest const&) & noexcept = default;
        FileUpdateRequest& operator=(FileUpdateRequest&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileUpdateRequestDeferral : Windows::Storage::Provider::IFileUpdateRequestDeferral
    {
        FileUpdateRequestDeferral(std::nullptr_t) noexcept {}
        FileUpdateRequestDeferral(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IFileUpdateRequestDeferral(ptr, take_ownership_from_abi) {}
        FileUpdateRequestDeferral(FileUpdateRequestDeferral const&) noexcept = default;
        FileUpdateRequestDeferral(FileUpdateRequestDeferral&&) noexcept = default;
        FileUpdateRequestDeferral& operator=(FileUpdateRequestDeferral const&) & noexcept = default;
        FileUpdateRequestDeferral& operator=(FileUpdateRequestDeferral&&) & noexcept = default;
    };
    struct __declspec(empty_bases) FileUpdateRequestedEventArgs : Windows::Storage::Provider::IFileUpdateRequestedEventArgs
    {
        FileUpdateRequestedEventArgs(std::nullptr_t) noexcept {}
        FileUpdateRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IFileUpdateRequestedEventArgs(ptr, take_ownership_from_abi) {}
        FileUpdateRequestedEventArgs(FileUpdateRequestedEventArgs const&) noexcept = default;
        FileUpdateRequestedEventArgs(FileUpdateRequestedEventArgs&&) noexcept = default;
        FileUpdateRequestedEventArgs& operator=(FileUpdateRequestedEventArgs const&) & noexcept = default;
        FileUpdateRequestedEventArgs& operator=(FileUpdateRequestedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderFileTypeInfo : Windows::Storage::Provider::IStorageProviderFileTypeInfo
    {
        StorageProviderFileTypeInfo(std::nullptr_t) noexcept {}
        StorageProviderFileTypeInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderFileTypeInfo(ptr, take_ownership_from_abi) {}
        StorageProviderFileTypeInfo(param::hstring const& fileExtension, param::hstring const& iconResource);
        StorageProviderFileTypeInfo(StorageProviderFileTypeInfo const&) noexcept = default;
        StorageProviderFileTypeInfo(StorageProviderFileTypeInfo&&) noexcept = default;
        StorageProviderFileTypeInfo& operator=(StorageProviderFileTypeInfo const&) & noexcept = default;
        StorageProviderFileTypeInfo& operator=(StorageProviderFileTypeInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderGetContentInfoForPathResult : Windows::Storage::Provider::IStorageProviderGetContentInfoForPathResult
    {
        StorageProviderGetContentInfoForPathResult(std::nullptr_t) noexcept {}
        StorageProviderGetContentInfoForPathResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderGetContentInfoForPathResult(ptr, take_ownership_from_abi) {}
        StorageProviderGetContentInfoForPathResult();
        StorageProviderGetContentInfoForPathResult(StorageProviderGetContentInfoForPathResult const&) noexcept = default;
        StorageProviderGetContentInfoForPathResult(StorageProviderGetContentInfoForPathResult&&) noexcept = default;
        StorageProviderGetContentInfoForPathResult& operator=(StorageProviderGetContentInfoForPathResult const&) & noexcept = default;
        StorageProviderGetContentInfoForPathResult& operator=(StorageProviderGetContentInfoForPathResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderGetPathForContentUriResult : Windows::Storage::Provider::IStorageProviderGetPathForContentUriResult
    {
        StorageProviderGetPathForContentUriResult(std::nullptr_t) noexcept {}
        StorageProviderGetPathForContentUriResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderGetPathForContentUriResult(ptr, take_ownership_from_abi) {}
        StorageProviderGetPathForContentUriResult();
        StorageProviderGetPathForContentUriResult(StorageProviderGetPathForContentUriResult const&) noexcept = default;
        StorageProviderGetPathForContentUriResult(StorageProviderGetPathForContentUriResult&&) noexcept = default;
        StorageProviderGetPathForContentUriResult& operator=(StorageProviderGetPathForContentUriResult const&) & noexcept = default;
        StorageProviderGetPathForContentUriResult& operator=(StorageProviderGetPathForContentUriResult&&) & noexcept = default;
    };
    struct StorageProviderItemProperties
    {
        StorageProviderItemProperties() = delete;
        static auto SetAsync(Windows::Storage::IStorageItem const& item, param::async_iterable<Windows::Storage::Provider::StorageProviderItemProperty> const& itemProperties);
    };
    struct __declspec(empty_bases) StorageProviderItemProperty : Windows::Storage::Provider::IStorageProviderItemProperty
    {
        StorageProviderItemProperty(std::nullptr_t) noexcept {}
        StorageProviderItemProperty(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderItemProperty(ptr, take_ownership_from_abi) {}
        StorageProviderItemProperty();
        StorageProviderItemProperty(StorageProviderItemProperty const&) noexcept = default;
        StorageProviderItemProperty(StorageProviderItemProperty&&) noexcept = default;
        StorageProviderItemProperty& operator=(StorageProviderItemProperty const&) & noexcept = default;
        StorageProviderItemProperty& operator=(StorageProviderItemProperty&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderItemPropertyDefinition : Windows::Storage::Provider::IStorageProviderItemPropertyDefinition
    {
        StorageProviderItemPropertyDefinition(std::nullptr_t) noexcept {}
        StorageProviderItemPropertyDefinition(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderItemPropertyDefinition(ptr, take_ownership_from_abi) {}
        StorageProviderItemPropertyDefinition();
        StorageProviderItemPropertyDefinition(StorageProviderItemPropertyDefinition const&) noexcept = default;
        StorageProviderItemPropertyDefinition(StorageProviderItemPropertyDefinition&&) noexcept = default;
        StorageProviderItemPropertyDefinition& operator=(StorageProviderItemPropertyDefinition const&) & noexcept = default;
        StorageProviderItemPropertyDefinition& operator=(StorageProviderItemPropertyDefinition&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderKnownFolderEntry : Windows::Storage::Provider::IStorageProviderKnownFolderEntry
    {
        StorageProviderKnownFolderEntry(std::nullptr_t) noexcept {}
        StorageProviderKnownFolderEntry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderKnownFolderEntry(ptr, take_ownership_from_abi) {}
        StorageProviderKnownFolderEntry();
        StorageProviderKnownFolderEntry(StorageProviderKnownFolderEntry const&) noexcept = default;
        StorageProviderKnownFolderEntry(StorageProviderKnownFolderEntry&&) noexcept = default;
        StorageProviderKnownFolderEntry& operator=(StorageProviderKnownFolderEntry const&) & noexcept = default;
        StorageProviderKnownFolderEntry& operator=(StorageProviderKnownFolderEntry&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderKnownFolderSyncInfo : Windows::Storage::Provider::IStorageProviderKnownFolderSyncInfo
    {
        StorageProviderKnownFolderSyncInfo(std::nullptr_t) noexcept {}
        StorageProviderKnownFolderSyncInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderKnownFolderSyncInfo(ptr, take_ownership_from_abi) {}
        StorageProviderKnownFolderSyncInfo();
        StorageProviderKnownFolderSyncInfo(StorageProviderKnownFolderSyncInfo const&) noexcept = default;
        StorageProviderKnownFolderSyncInfo(StorageProviderKnownFolderSyncInfo&&) noexcept = default;
        StorageProviderKnownFolderSyncInfo& operator=(StorageProviderKnownFolderSyncInfo const&) & noexcept = default;
        StorageProviderKnownFolderSyncInfo& operator=(StorageProviderKnownFolderSyncInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderKnownFolderSyncRequestArgs : Windows::Storage::Provider::IStorageProviderKnownFolderSyncRequestArgs
    {
        StorageProviderKnownFolderSyncRequestArgs(std::nullptr_t) noexcept {}
        StorageProviderKnownFolderSyncRequestArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderKnownFolderSyncRequestArgs(ptr, take_ownership_from_abi) {}
        StorageProviderKnownFolderSyncRequestArgs(StorageProviderKnownFolderSyncRequestArgs const&) noexcept = default;
        StorageProviderKnownFolderSyncRequestArgs(StorageProviderKnownFolderSyncRequestArgs&&) noexcept = default;
        StorageProviderKnownFolderSyncRequestArgs& operator=(StorageProviderKnownFolderSyncRequestArgs const&) & noexcept = default;
        StorageProviderKnownFolderSyncRequestArgs& operator=(StorageProviderKnownFolderSyncRequestArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderMoreInfoUI : Windows::Storage::Provider::IStorageProviderMoreInfoUI
    {
        StorageProviderMoreInfoUI(std::nullptr_t) noexcept {}
        StorageProviderMoreInfoUI(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderMoreInfoUI(ptr, take_ownership_from_abi) {}
        StorageProviderMoreInfoUI();
        StorageProviderMoreInfoUI(StorageProviderMoreInfoUI const&) noexcept = default;
        StorageProviderMoreInfoUI(StorageProviderMoreInfoUI&&) noexcept = default;
        StorageProviderMoreInfoUI& operator=(StorageProviderMoreInfoUI const&) & noexcept = default;
        StorageProviderMoreInfoUI& operator=(StorageProviderMoreInfoUI&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderQueryResultSet : Windows::Storage::Provider::IStorageProviderQueryResultSet
    {
        StorageProviderQueryResultSet(std::nullptr_t) noexcept {}
        StorageProviderQueryResultSet(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderQueryResultSet(ptr, take_ownership_from_abi) {}
        explicit StorageProviderQueryResultSet(array_view<Windows::Storage::Provider::IStorageProviderQueryResult const> results);
        StorageProviderQueryResultSet(StorageProviderQueryResultSet const&) noexcept = default;
        StorageProviderQueryResultSet(StorageProviderQueryResultSet&&) noexcept = default;
        StorageProviderQueryResultSet& operator=(StorageProviderQueryResultSet const&) & noexcept = default;
        StorageProviderQueryResultSet& operator=(StorageProviderQueryResultSet&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderQuotaUI : Windows::Storage::Provider::IStorageProviderQuotaUI
    {
        StorageProviderQuotaUI(std::nullptr_t) noexcept {}
        StorageProviderQuotaUI(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderQuotaUI(ptr, take_ownership_from_abi) {}
        StorageProviderQuotaUI();
        StorageProviderQuotaUI(StorageProviderQuotaUI const&) noexcept = default;
        StorageProviderQuotaUI(StorageProviderQuotaUI&&) noexcept = default;
        StorageProviderQuotaUI& operator=(StorageProviderQuotaUI const&) & noexcept = default;
        StorageProviderQuotaUI& operator=(StorageProviderQuotaUI&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderSearchQueryOptions : Windows::Storage::Provider::IStorageProviderSearchQueryOptions
    {
        StorageProviderSearchQueryOptions(std::nullptr_t) noexcept {}
        StorageProviderSearchQueryOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderSearchQueryOptions(ptr, take_ownership_from_abi) {}
        StorageProviderSearchQueryOptions(StorageProviderSearchQueryOptions const&) noexcept = default;
        StorageProviderSearchQueryOptions(StorageProviderSearchQueryOptions&&) noexcept = default;
        StorageProviderSearchQueryOptions& operator=(StorageProviderSearchQueryOptions const&) & noexcept = default;
        StorageProviderSearchQueryOptions& operator=(StorageProviderSearchQueryOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderSearchResult : Windows::Storage::Provider::IStorageProviderSearchResult,
        impl::require<StorageProviderSearchResult, Windows::Storage::Provider::IStorageProviderQueryResult>
    {
        StorageProviderSearchResult(std::nullptr_t) noexcept {}
        StorageProviderSearchResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderSearchResult(ptr, take_ownership_from_abi) {}
        StorageProviderSearchResult();
        StorageProviderSearchResult(StorageProviderSearchResult const&) noexcept = default;
        StorageProviderSearchResult(StorageProviderSearchResult&&) noexcept = default;
        StorageProviderSearchResult& operator=(StorageProviderSearchResult const&) & noexcept = default;
        StorageProviderSearchResult& operator=(StorageProviderSearchResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderStatusUI : Windows::Storage::Provider::IStorageProviderStatusUI
    {
        StorageProviderStatusUI(std::nullptr_t) noexcept {}
        StorageProviderStatusUI(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderStatusUI(ptr, take_ownership_from_abi) {}
        StorageProviderStatusUI();
        StorageProviderStatusUI(StorageProviderStatusUI const&) noexcept = default;
        StorageProviderStatusUI(StorageProviderStatusUI&&) noexcept = default;
        StorageProviderStatusUI& operator=(StorageProviderStatusUI const&) & noexcept = default;
        StorageProviderStatusUI& operator=(StorageProviderStatusUI&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderSuggestionResult : Windows::Storage::Provider::IStorageProviderQueryResult
    {
        StorageProviderSuggestionResult(std::nullptr_t) noexcept {}
        StorageProviderSuggestionResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderQueryResult(ptr, take_ownership_from_abi) {}
        StorageProviderSuggestionResult();
        StorageProviderSuggestionResult(StorageProviderSuggestionResult const&) noexcept = default;
        StorageProviderSuggestionResult(StorageProviderSuggestionResult&&) noexcept = default;
        StorageProviderSuggestionResult& operator=(StorageProviderSuggestionResult const&) & noexcept = default;
        StorageProviderSuggestionResult& operator=(StorageProviderSuggestionResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderSuggestionsQueryOptions : Windows::Storage::Provider::IStorageProviderSuggestionsQueryOptions
    {
        StorageProviderSuggestionsQueryOptions(std::nullptr_t) noexcept {}
        StorageProviderSuggestionsQueryOptions(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderSuggestionsQueryOptions(ptr, take_ownership_from_abi) {}
        StorageProviderSuggestionsQueryOptions(StorageProviderSuggestionsQueryOptions const&) noexcept = default;
        StorageProviderSuggestionsQueryOptions(StorageProviderSuggestionsQueryOptions&&) noexcept = default;
        StorageProviderSuggestionsQueryOptions& operator=(StorageProviderSuggestionsQueryOptions const&) & noexcept = default;
        StorageProviderSuggestionsQueryOptions& operator=(StorageProviderSuggestionsQueryOptions&&) & noexcept = default;
    };
    struct __declspec(empty_bases) StorageProviderSyncRootInfo : Windows::Storage::Provider::IStorageProviderSyncRootInfo,
        impl::require<StorageProviderSyncRootInfo, Windows::Storage::Provider::IStorageProviderSyncRootInfo2, Windows::Storage::Provider::IStorageProviderSyncRootInfo3>
    {
        StorageProviderSyncRootInfo(std::nullptr_t) noexcept {}
        StorageProviderSyncRootInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Storage::Provider::IStorageProviderSyncRootInfo(ptr, take_ownership_from_abi) {}
        StorageProviderSyncRootInfo();
        StorageProviderSyncRootInfo(StorageProviderSyncRootInfo const&) noexcept = default;
        StorageProviderSyncRootInfo(StorageProviderSyncRootInfo&&) noexcept = default;
        StorageProviderSyncRootInfo& operator=(StorageProviderSyncRootInfo const&) & noexcept = default;
        StorageProviderSyncRootInfo& operator=(StorageProviderSyncRootInfo&&) & noexcept = default;
    };
    struct StorageProviderSyncRootManager
    {
        StorageProviderSyncRootManager() = delete;
        static auto Register(Windows::Storage::Provider::StorageProviderSyncRootInfo const& syncRootInformation);
        static auto Unregister(param::hstring const& id);
        static auto GetSyncRootInformationForFolder(Windows::Storage::IStorageFolder const& folder);
        static auto GetSyncRootInformationForId(param::hstring const& id);
        static auto GetCurrentSyncRoots();
        static auto IsSupported();
    };
}
#endif
